### PR TITLE
Sasview counterpart to sasdata manipulations rewrite

### LINKED ISSUE #2593: Neither fold=True nor fold=False is appropriate for WedgeSlicer
** Describe the issue **
The wedge slicer (specifically `WedgeInteractorQ`) is build on the same foundations as the sector slicer. With this comes "fold" functionality, which when enabled averages the data in the region of interest with the data on the opposite side of the origin. When fold is disabled, data on the opposite side of the origin to the main ROI is shown plotted against negative Q values. This is the current state of wedge slicer, but I had been unaware until recently that these negative Q values were present as the default graph scale is log-log, which obscures the negative Q values.
Neither of these fold behaviours are desired for the wedge slicer.

** Expected behaviour **
Only data enclosed within the main ROI should be plotted. 

** To reproduce **
1. In Sasview, Compute/Plot any 2D data from `example_data/2d_data`, using any model.
2. Right click the plot and select 'Wedge Averaging in Q'.
3. Change the scale of the output graph to linear, and observe that negative Q values are also plotted, corresponding to data outside the ROI.

** Additional context **
The proper fix (in my opinion) would be editing the `_Sector` class in `sasdata/sasdata/data_util/manipulations.py` to provide a third alternative to `self.fold = True` or `self.fold = False`, one which only processes the data within the specified region of interest. This could make the current version of `_Sector` even more confusing however, so I would rather work this into the `manipulations.py` rewrite and use a simpler fix in the meantime. This would involve adding some code to `WedgeSlicer.py` which looks for data associated with negative Q values in the `Data1D` object returned by `_Sector`, then discarding it before plotting.
If/When a method for handling this is added on the `manipulations.py` side, the commit fixing this issue can be kept or reverted with no ill effect.

### PR DESCRIPTION
**Pull request by ehewins**
## Description

This pull request, as the title suggests, is the sasview counterpart to my rewrite of sasdata's `manipulations.py`. Full details are given in [this pull request](https://github.com/SasView/sasdata/pull/47). 

Fixes #2593 

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [X] User documentation is available and complete (if required)
- [X] Developers documentation is available and complete (if required)
- [X] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by krzywon** [comment]
Everything here looks fine, but I have a few suggestions.

1. If `sasdata.data_util.manipulations.py` is no longer used, replace it.
2. To test the SasView build using unmerged changes in dependent repos, modify `.github/workflows/ci.yml`, replacing `master` in `git clone --depth=50 --branch=master https://github.com/SasView/<repo>.git ../<repo>` with the name of your branch, but be sure to revert back before merging.

**Comment by wpotrzebowski** [comment]
@ehewins will you be willing to take a look on @krzywon suggestions? No worries if not - we need to know how to move forward with it.

**Comment by ehewins** [comment]
Hi @wpotrzebowski , apologies about the lack of activity recently. I wish I could, but university work has completely taken over my life at the moment. I had wanted to do some more work on my unit test file in the other repo, and was up for doing this too, but I don't think I'll have time until several weeks from now.
Realistically I think your best option is to assume I won't be doing any more work on the area. I might surprise you all with a commit or two about a month from now though (if I can organise my time well enough).

**Comment by wpotrzebowski** [comment]
@krzywon will take a quick look at it

**Comment by krzywon** [comment]
I have a commit to push here, but want to be sure the changes I made in sasview/sasdata#47 are acceptable, so I don't pollute two different PRs. The changes have to do with the file name change (from `maniuplations_new.py` to `averaging.py`).

**Comment by krzywon** [comment]
This PR and the associated one, sasview/sasdata#47, are ready for a full review. The CI for this PR points to the associated sasdata branch and should be changed prior to merging.

**Comment by jack-rooks** [comment]
Using the requirements specified by this branch (following [the setup guide](https://github.com/SasView/sasview/wiki/DevNotes_CondaDevEnviroment)) results in a problem for matplotlib 3.5.3 (https://github.com/matplotlib/matplotlib/issues/24374)

Can be fixed by following the solution there (installing matplotlib 3.6.2). Assuming I followed the correct install procedure it may be necessary to update build_tools/requirements.txt to have `matplotlib==3.6.2`)

**Comment by lucas-wilkins** [comment]
Closing because too out of sync, not deleting branch though

**Pull request closed without merging**
