### PR TITLE
Added missing dependencies to requirements.txt

### PR DESCRIPTION
**Pull request by lucas-wilkins**
Resolves recent issue #2126

### CODE REVIEW

**Comment by butlerpd** [comment]
I think we should add @wpotrzebowski to the review since he was the one last working on fine tuning requirements.txt.  Just in case there was something special we are missing here?

**Comment by lucas-wilkins** [comment]
> I think we should add @wpotrzebowski to the review since he was the one last working on fine tuning requirements.txt. Just in case there was something special we are missing here?

I meant to.

**Comment by lucas-wilkins** [comment]
@wpotrzebowski I've removed the OS dependency - can you check I used the right versions (I picked the windows/linux associated ones)

**Review by wpotrzebowski — COMMENTED** [review]
Do we need "pyqt5-tools" if we already have PyQt5?

**Review by wpotrzebowski — CHANGES_REQUESTED** [review]
importlib_resources seems to refer to importlib-resources i.e. does it appear twice on the list?

**Comment by wpotrzebowski** [comment]
Probablty not as a part of this pull request but it may be worth to set up GH actions that "tests" requirements.txt file when change is made in it. By testing I mean pip installing on workers.

**Comment by lucas-wilkins** [comment]
importlib_resources seems to refer to importlib-resources i.e. does it appear twice on the list?

They're for different python versions - though as we discussed recently, there is no need to support python < 3.7, so the former is not really needed.

**Review by wpotrzebowski — APPROVED** [review]
Tested on Mac. It works fine

**Pull request merged**
