### PR TITLE
Add long sesans file test example

### PR DESCRIPTION
**Pull request by rprospero**
This just adds another spin echo example file.  This is useful for simulating larger SESANS samples.

### CODE REVIEW

**Comment by butlerpd** [comment]
What is the purpose of this file?  It is being added to the unit tests directory (which seems oddly structured anyway).  If this is meant to catch problems from changes to the reader this is appropriate but if it is an example file the user might want to load as suggested by the PR comment it is not. In that case it should be added to sasview/src/sas/sasview/test/sesans_data

**Comment by rprospero** [comment]
I've moved the file to the location that you suggested, since its primary use is as an example file.

**Comment by butlerpd** [comment]
ready for testing on Win64

**Comment by butlerpd** [comment]
ready for testing on Win64

**Pull request merged**
