### PR TITLE
6.0.0: Final Fixes

### PR DESCRIPTION
**Pull request by krzywon**
## Description
This is a series of changes that are needed for the final 6.0.0 release. Items changed in this PR:

- Added @jamescrake-merani to the contributors TSV list
- Cherry-picked https://github.com/SasView/sasview/pull/3090/commits/fb93303cd4767322ed883a14c6ea898b593918dd from #3090 
- Fixed the issue caused by fits going outside of the GSC model range. The calculated values were `NaN` which isn't plottable. (Note, this is a quick hack to access a sasdata class method that should really be its own function.)
- Moved to the release tags for SasData and SasModels to ensure frozen code.
- Fixed optimizer loading described in https://github.com/orgs/SasView/discussions/3116#discussioncomment-10906801

**ANY OTHER FIXES MAY GO HERE**

Refs https://github.com/orgs/SasView/discussions/3116

## Review Checklist:

[if using the editor, use `[x]` in place of `[ ]` to check a box]

**Documentation** (check at least one)
- [x] There is **nothing** that needs documenting
- [ ] Documentation changes are **in this PR**
- [ ] There is an **issue** open for the documentation (link?)

**Installers**
- [x] There is a chance this will affect the **installers**, if so
  - [x] **Windows** installer (GH artifact) has been tested (installed and worked) 
  - [x] **MacOSX** installer (GH artifact) has been tested (installed and worked) 

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by rozyczko** [comment]
Hmm the installation doesn't work for me (Win10, 64bit).
Still getting 
```
sas.system.config.config_meta.MalformedFile: Malformed version in config file, should be a string of the form 'X.Y.Z'
```
and SasView window doesn't show up

**Review by lucas-wilkins — APPROVED** [review]
@jamescrake-merani and I looked at code, checked installers on windows and mac, LGTM!!

**Comment by wpotrzebowski** [comment]
I am getting the following error when with fitting with DREAM:
`21:41:40 - ERROR: Fitting failed: Traceback (most recent call last): File "sas/qtgui/Perspectives/Fitting/FitThread.py", line 79, in compute File "sas/qtgui/Perspectives/Fitting/FitThread.py", line 19, in map_apply File "sas/qtgui/Perspectives/Fitting/FitThread.py", line 16, in map_getattr File "sas/sascalc/fit/BumpsFitting.py", line 285, in fit IndexError: tuple index out of range
21:41:40 - ERROR: tuple index out of range === Steps: 1101 of 1100 chisq: 117 ETA: 2024-10-12 21:41 (0s from now) M1.radius : 14 |
21:41:40 - ERROR: Traceback (most recent call last): File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 2121, in fitComplete AttributeError: 'str' object has no attribute 'fitness'`

I think we fixed it at some point?

**Comment by wpotrzebowski** [comment]
I guess we need to pull #3110

**Comment by krzywon** [comment]
> I guess we need to pull #3110

The builds from this branch use bumps v0.9.2. #3110 should have no bearing on this. If you are running from source, be sure you checkout bumps tag=v0.9.2.

**Comment by wpotrzebowski** [comment]
> > I guess we need to pull #3110
> 
> The builds from this branch use bumps v0.9.2. #3110 should have no bearing on this. If you are running from source, be sure you checkout bumps tag=v0.9.2.

I've been running from the MAC installer.

**Comment by krzywon** [comment]
> > > I guess we need to pull #3110
> > 
> > 
> > The builds from this branch use bumps v0.9.2. #3110 should have no bearing on this. If you are running from source, be sure you checkout bumps tag=v0.9.2.
> 
> I've been running from the MAC installer.

Then the DREAM error will need to be investigated. Can you reliably reproduce the issue?

**Comment by wpotrzebowski** [comment]
The error I see is very reproducible. I've tested both arm and x86 installer and it is reproducible. It appears no matter which fit algorithm I use before switching to DREAM. The error also appears regardless if I choose Default Fit algorithm or Fit Algorithm

https://github.com/user-attachments/assets/f6be833b-09c6-46cf-bb3a-d4f5f274e3dd

**Comment by krzywon** [comment]
@wpotrzebowski - I can reproduce it on Windows as well. This is going to hold up the release.

**Comment by krzywon** [comment]
The issue noted by @wpotrzebowski is going to hold up the release. I've been trying to diagnose this and can't find a proper solution. In the mean time, I'm merging this PR so the release branch is up to date

**Pull request merged**
