### PR TITLE
Ticket 741

### PR DESCRIPTION
**Pull request by lewisodriscoll**
Fixes ticket [#741](http://trac.sasview.org/ticket/741) - plotting of P(Q) and S(Q)

Requires sasmodels pull request [#41](https://github.com/SasView/sasmodels/pull/41) to run correctly

Code has already been reviewed; just needs functional testing

### CODE REVIEW

**Comment by RichardHeenan** [comment]
Looks good to me, have spent a while trying to break it.
P(Q),S(Q) and unsmeared are now "special", they auto-update on any plot where they appear. Most users will likely simply append them to the plot with their fit. Now need to check in the docs that we tell users how to do this!
Richard

**Comment by RichardHeenan** [comment]
Where do I click to “review” this?  I left a “comment”, but I only have buttons for ”comment” or “close pull request” ???
Richard

**Comment by butlerpd** [comment]
When you open the pull request you have 3 tabs.  You default to tab 1
"Conversations" which is where you see all the comments.  The second is
"commits" and the third is "Files Changed"

If you click on the 3rd tab you will see a green button at the top right
that says "Add your review"  ... assuming you are logged in as you :-)
 This is where you type in your official review and either approve or ask
for changes

Paul

**Comment by RichardHeenan** [comment]
Ah, I had got there once before …
No idea why this went to you Paul not to Lewis!
Richard

**Pull request merged**
