### PR TITLE
Move builds to use matplotlib 3.5.x

### LINKED ISSUE #2222: Breaking change in setuptools 50+
**Describe the bug**

Running GitHub workflow-generated installers on Windows, the following error occurs:
> Traceback (most recent call last):
>   File "sasview.py", line 15, in <module>
>   File "sas\qtgui\MainWindow\MainWindow.py", line 120, in run_sasview
>   File "sas\qtgui\MainWindow\MainWindow.py", line 46, in __init__
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "sas\qtgui\MainWindow\GuiManager.py", line 14, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "matplotlib\__init__.py", line 112, in <module>
>   File "_distutils_hack\__init__.py", line 88, in create_module
>   File "importlib\__init__.py", line 127, in import_module
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "setuptools\__init__.py", line 10, in <module>
>   File "_distutils_hack\__init__.py", line 88, in create_module
>   File "importlib\__init__.py", line 127, in import_module
> ModuleNotFoundError: No module named 'setuptools._distutils'

There is an [issue](https://github.com/pypa/setuptools/issues/2353) in the `setuptools` repo describing the change and potential workarounds, but I haven't read the full thread yet.

**To Reproduce**
Download a recent windows installer generated by a push or PR, install the software, and try to run sasview.

**SasView version (please complete the following information):**
 - Version: post 5.0.5

### PR DESCRIPTION
**Pull request by llimeht**
Updating matplotlib to version 3.5.x means that the conflicting pinning and bugs in setuptools for matplotlib vs setuptools vs numba is avoided.

This _should_ fix #2222.

This PR necessarily includes the commits from #2216 and #2213.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
I've just tried Mac installer from this PR and I am still getting error: 
`ModuleNotFoundError: No module named 'setuptools._distutils'`

**Comment by wpotrzebowski** [comment]
Mac installer works now!

**Review by wpotrzebowski — COMMENTED** [review]
There was a discussion some time ago about strict versions and I think we concluded that we want to keep them (at least that's what I remmber).

**Comment by wpotrzebowski** [comment]
Can someone test Windows installer?

**Comment by llimeht** [comment]
> There was a discussion some time ago about strict versions and I think we concluded that we want to keep them (at least that's what I remmber).

Sticking to PEP440 versions is a good idea. Importing and running `StrictVersion(foo)` doesn't actually do anything, however. (Well, it would raise a `ValueError` if the version is bad, but that's a thing to check at build time not every time you start SasView).

With distutils going away, there's not actually a long term option to keep that call to StrictVersion there in any case.

**Comment by krzywon** [comment]
> Can someone test Windows installer?

I just tested the Windows installer and SasView launched as expected.

> There was a discussion some time ago about strict versions and I think we concluded that we want to keep them (at least that's what I remmber).

Thre was a recent discussion in PR #2168, specifically [this comment chain](https://github.com/SasView/sasview/pull/2168#discussion_r971288691) but I think there was mention of it again in that PR as well.

**Comment by wpotrzebowski** [comment]
@lucas-wilkins did you have a chance to look at it?

**Comment by lucas-wilkins** [comment]
> @lucas-wilkins did you have a chance to look at it?

@wpotrzebowski Not this one, but its a continuation of #2213 right? I approved that one, and this appears to just add the updates to `requirements.txt` and another PR.

Regarding the StrictVersion thing, we can do proper versioning without calling the `StrictVersion` constructor in `__init__`. 

@krzywon There are likely some conflicts, they'll just have to be sorted by whoever merges last.

**Comment by llimeht** [comment]
Rebased onto current `main` and trivial conflict in .spec file (automatically) resolved.

**Pull request merged**
