### PR TITLE
Adding h5py=3.1 as a pip package

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Since conda package is conflicting and cannot be resolved I am trying with pip installable package

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Windows

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
Tested with PR builders and seems to build but I am not sure if this way to go?

**Review by rozyczko — APPROVED** [review]
looks good to me

**Comment by krzywon** [comment]
The PR builds succeed, which is good, but the installed Windows version is still showing the `No module named 'sas.sascalc.dataloader.readers.cansas_reader_HDF5'` error. I'm going to try using a slightly older version of h5py to see if we can fix both issues in one.

**Review by krzywon — APPROVED** [review]

**Pull request merged**
