### PR TITLE
A Code of Conduct for Open Source Projects

### PR DESCRIPTION
**Pull request by wpotrzebowski**
This is a proposal of code of conduct from https://www.contributor-covenant.org/ that can be used by any open source project. There is no code for this pull request - only *.md file.  Everyone is welcome to review it. Once we agree on it, I will also make it available from ESS_GUI.

### CODE REVIEW

**Comment by RichardHeenan** [comment]
Looks OK to me,
Richard

**Comment by butlerpd** [comment]
I have a few concerns, the first being that it is quite lengthy. On the one hand it makes it seem like a bunch of legalize that you just want to go to the bottom of and click “accept” rather than something being taken seriously, and on the other it is easier for the authors to not realize exactly the full impact of what they are stating?
Looking around for other things (python boot camps) I found this website, [https://codecamp.org/](https://codecamp.org/) which seems quite interesting and also had a code of conduct which is much shorter (one paragraph short version and a 4 short paragraphs long version) and seems a bit more impactful?
 
### RALEIGH CODE CAMP CODE OF CONDUCT
All attendees, speakers, sponsors and volunteers at Raleigh Code Camp are required to agree with the following code of conduct. Organizers will enforce this code throughout all events.

Quick Version
The Raleigh Code Camp is dedicated to providing a harassment-free experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, or religion. We do not tolerate harassment of event participants in any form. Sexual language and imagery is not appropriate for any event venue, including group organized meetings and Code Camps. Event participants violating these rules may be sanctioned or expelled from the event and/or future events at the discretion of the group leadership.

Detailed Version
Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately.

If a participant engages in harassing behavior, the group leadership may take any action they deem appropriate, including warning the offender or expulsion from group events. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of the Raleigh Code Camp leadership immediately.

The Raleigh Code Camp leadership team will be happy to help participants contact venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of a Raleigh Code Camp event or meeting. We value your attendance.

We expect participants to follow these rules at all event venues and Raleigh Code Camp related social events. Please direct any questions or concerns to info (at) codecamp.org.

--------------------------

Otherwise, some specific concerns I have
- We don’t have an “enforcement” leadership - it is more of a management group that tries to pull together the consensus.
- Diversity is listed as being quite broad but examples of bad behavior seem to focus mostly on sexual misconduct.  There is plenty of non-sexual imagery or behavior that can be very problematic.
- The tone seems to me slightly off for a global community effort?
- Most importantly though, I would argue that we should not be just trying to avoid different people feeling harassed we should be proactively engaging them and actively working to make them welcome.

In that vein here is a rough first cut at a two paragraph statement that tries to capture such a more positive stance? 
 
As a community, collaborative development model, everyone interested in scattering, and particularly small angle scattering, are potentially part of the community and invited to participate in the SasView collaborative effort. As such the SasView community aims to not only be open and harassment-free, but actively inviting and engaging to everyone regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, sexual identity and orientation, or any other distinguishing characteristic that could be viewed as “different.”

Fundamentally, the SasView community believes differences should be recognized and celebrated not harassed or shamed. That said it is also recognized that the realities of vastly different experiences and perspectives may lead to tensions which can escalate to at least the perception of harassment by one or another party.  When such instances occur and cannot, for whatever reason, be resolved by frank dialogue between the parties, or as soon as any party feels unsafe, these should be brought to the attention of the management team.  The management team will take whatever action is appropriate to ensure everyone’s comfort and safety, but will first endeavor whenever possible to resolve the issues through dialogue and communication that promotes mutual understanding and respect. However in egregious cases, and for cases where the offending activity continues unabated, the management team will remove access to SasView contribution resources and ban the person from participating in group activities such as code camps.

**Comment by krzywon** [comment]
I think the Raleigh code camp code of conduct is too narrow focused towards code camps, failure to follow the rules has no explicit punishment, and the burden of punishment and protection falls too heavily on the community leadership.

If we are voting, I think the one proposed in this PR is the better of the options.

**Comment by ajj** [comment]
I agree with @butlerpd that we need something a bit more tailored and pithy that we could include e.g. on the website

**Comment by smk78** [comment]
It is truly sad that such things should need to be spelt out. And I am, unfortunately, reminded of the 'passionate' agonising that two, small, member-led sports clubs, I belong too, went through a few years ago when well-intentioned legislation to protect a vunerable group of the population created a bureaucratic nightmare for voluntary organisations. Indeed, the resolution in both instances was for us to simply exclude that very group from participation in club events except in very, very, specific circumstances; because that was the only way our limited resources allowed us to comply. So the lessons that I bring to this discussion, from hard experience, are 'less is more' and 'keep it proportionate'. On that basis I think @butlerpd is pretty close to the right length and tone. But it should be a living document. When we are content, it should be placed on the website and in the top-level of the SasView repo.

**Comment by butlerpd** [comment]
So to move forward on this project It looks to me like we have the following tasks:
- [ ] Agree on whether some statement on this topic is necessary/appropriate for the current size/resources of the project. If yes then:
  - [ ] Agree on appropriate level and tone of such a statement at this time 
  - [ ] Agree how such a statement is managed (where is the master copy kept, where else does it get published, how "living" should it be and how do changes get made)
  - [ ] Agree draft wording
  - [ ] Finalize wording
  - [ ] post in appropriate places

**Pull request closed without merging**
