### PR TITLE
Constraint on parameter raises error

### LINKED ISSUE #2695: constraint on parameter raises error
**Describe the bug**
Trying to set a constraint on a parameter in 6.0.0 alpha throws a Traceback error
```
Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1053, in editConstraint File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1053, in File "sas\qtgui\Perspectives\Fitting\FittingUtilities.py", line 968, in isParamPolydisperse TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**
1. load a data set (I used apoferritin)
2. send to fitting
3. choose a model (I used core shell sphere)
4. Select a parameter (I chose thickness)
5. Right click on that parameter and choose `Constrain parameter to its current value` from the drop down
6. Right click on same parameter and now choose `Edit constraint` from the drop down
7. The error is thrown

**Expected behavior**
Instead of an error there should be a box to enter a constraint

**SasView version (please complete the following information):**
 - Version: 6.0.0 alpha build from Dec 19, 2023

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
suspect this may be another pyside issue?

### PR DESCRIPTION
**Pull request by rozyczko**
## Description

Some of the logic was incorrect, when setting the single-parameter constraint and when querying the underlying model information.
Now, item query returns proper parameter names, and the context menu is properly constructed (i.e. no "Edit constraint" on simple value constraint added)

Fixes #2695 

## How Has This Been Tested?

Local dev build on Win10

## Review Checklist (please remove items if they don't apply):

- [x] Code has been reviewed
- [x] Functionality has been tested
- [x] Windows installer (GH artifact) has been tested (installed and worked) 
- [x] MacOSX installer (GH artifact) has been tested (installed and worked)

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
I've tested it on Mac and I don't seem to have access to "Edit Constrain" menu
Screenshot 2024-01-17 at 21 59 27
I've checked that it is avaialable in 5.0.6

**Comment by gonzalezma** [comment]
The edit option should appear when you have a definition in the Simultaneous fit tab. When you simple constraint one parameter to its current value, the option is not present. If this is not what you tested, then the behaviour on Windows and Mac seems to be different.

**Comment by wpotrzebowski** [comment]
I followed the steps described in https://github.com/SasView/sasview/issues/2695 and got different behavior with 5.0.6 and this build.

**Comment by gonzalezma** [comment]
Yes, that's true, but I think this was intended, judging from Piotr's description of the PR. I agree with him that when constraining a parameter to its current value, the edit button makes not much sense.

**Comment by wpotrzebowski** [comment]
OK, makes sense. I didn't read PR description properly.

**Comment by wpotrzebowski** [comment]
Tested again with newly build Mac and works fine. Following the same logic, wouldn't make sense to also remove "Select and Deselect" items? If I understand correctly they shouldn't affect parameter if it is constrained? If so, probably separate PR and not for 6.0 (as we are fixing bugs now).

**Review by wpotrzebowski — APPROVED** [review]

**Comment by danielballan** [comment]
Wow, what a great feature! Can't wait to see this merged!

**Comment by danielballan** [comment]
I sure wish @butlerpd would post a review.

**Review by butlerpd — CHANGES_REQUESTED** [review]
This is partly to test the request change but @krzywon says this is not how it worked in 5.0.6. Shouldn't we be keeping the functionality

**Comment by krzywon** [comment]
> This is partly to test the request change but @krzywon says this is not how it worked in 5.0.6. Shouldn't we be keeping the functionality

The issue has been discussed. The input box in the constraint editor is partly broken and requires more work, and will be reinstated once it has been resolved. That work is beyond the scope of this PR, so we should merge this.

**Pull request merged**
