### PR TITLE
Ticket 1616

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Preserving label and custom plot settings from being reset every time fit or comput has been executed.
A lot of GUI tests has been failing but mostly due to slicer changes

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by smk78** [comment]
Pulled this branch and built locally.
Loaded in the three AOT_Microemulsion datasets from \test\1d_data, checked them all and did Create New to get a plot.
Used the context menu to change the name of a dataset in the legend. This does seem to have been preserved no matter what other changes I applied.
Similarly, my change of title for the whole plot window seems to have stuck.
BUT
I changed the symbol and colour of a dataset and at some point the colour was randomly changed, I think after I brought up the plot navigation menu, went in to settings, changed a couple of values and exited.
I changed the X-axis label from the Q default to q, and at some point that got changed back to Q!
And whether I use the context menu Set Graph Range or the Navigation Settings to change the axis limits, the change is applied, but as soon as you do something else to the plot they automatically get reset!
As far as I can tell it is actually impossible to use any of the provided functionality to display a plot with more than one dataset in the colours, symbols, and on the axes, you want. :-(

**Comment by wpotrzebowski** [comment]
https://user-images.githubusercontent.com/4189922/104799041-114aed00-57cc-11eb-9d4a-916e974e3f84.mov

**Comment by wpotrzebowski** [comment]
@smk78 thanks for testing it. I would expect that at least some of your tests should work... Can you please check what happens when you follow steps from attached screen recording? (sorry for low quality but files cannot be bigger than 10MB).

**Comment by rozyczko** [comment]
> I think after I brought up the plot navigation menu, went in to settings, changed a couple of values and exited.
> I changed the X-axis label from the Q default to q, and at some point that got changed back to Q!
> And whether I use the context menu Set Graph Range or the Navigation Settings to change the axis limits

Ah, I see what the issue is. Anything that we can change from the plot context menu is retained. Anything that is applied from the MPL toolbar `Figure Options` is not stored, since it belongs to a different object which we don't track... I believe this was the main reason I didn't originally want the MPL toolbar to be there, since its options clash with our own chart options exposed in the context menu and tracked independently.
The zoom/pan/home buttons in the toolbar are the reason we have reenabled it, but little was done to the chart options in the toolbar.
Unfortunately, we can't easily remove the options button which would be the best solution.

I propose we treat these issues separately. This ticket addresses the properties we can easily control and this is what Wojtek did.
We may close it after code review.

We may open another ticket to address the MPL toolbar properties lifetime issues and I can start looking at it, unless Wojtek prefers to continue the effort?

**Review by rozyczko — APPROVED** [review]
Code looks good, extra points for cleaning up the syntax!

**Comment by butlerpd** [comment]
ready for testing on Win

**Review by butlerpd — APPROVED** [review]
The PR fixes what it advertises to fix on windows.  I vote this be merged.  The other issue with plot properties and separate and much larger and has its own issue I believe.

**Comment by smk78** [comment]
> @smk78 thanks for testing it. I would expect that at least some of your tests should work... Can you please check what happens when you follow steps from attached screen recording? (sorry for low quality but files cannot be bigger than 10MB).

@wpotrzebowski : if I follow your video I can reproduce the behaviour you demonstrate in W10.

**Comment by smk78** [comment]
Question: when you go into Modify Plot Property on the Residuals, change the label and font size and exit, the plot colour changes. Why is that? This is one of the 'quirks' I find irritating. With multiple plots you can end up with red and green data, which is obviously not ideal!

**Comment by wpotrzebowski** [comment]
Last commit should prevent annoying color change

**Comment by rozyczko** [comment]
> Last commit should prevent annoying color change

It's either this or using the `classic` style directive, but `classic` will sooner or later get deprecated so let's just switch to the "modern" way and use explicit hex codes for colours

**Comment by wpotrzebowski** [comment]
Merging this PR. Issues 5) and 6) from https://github.com/SasView/sasview/issues/1584 mentioned in the original ticket https://github.com/SasView/sasview/issues/1616 are still unresolved.

**Pull request merged**
