### PR TITLE
update list of coordinate testdata file

### PR DESCRIPTION
**Pull request by dehoni**

### CODE REVIEW

**Review by krzywon — APPROVED** [review]
I can't speak for the information given about the new files, but the formatting looks fine and the docs build properly.

**Comment by lucas-wilkins** [comment]
See #2176 for why your tests are failing, merge the associated branch for fix, or merge main when #2178 is merged in.

**Comment by lucas-wilkins** [comment]
@krzywon Was there a reason not to merge this? Feel like there might have been, but it's been here a while.

**Comment by krzywon** [comment]
> @krzywon Was there a reason not to merge this? Feel like there might have been, but it's been here a while.

I thought someone should review the content of the text before merging, otherwise, no.

**Comment by lucas-wilkins** [comment]
> > @krzywon Was there a reason not to merge this? Feel like there might have been, but it's been here a while.
> 
> I thought someone should review the content of the text before merging, otherwise, no.

Unless its factually incorrect, it looks fine.

**Comment by krzywon** [comment]
> > > @krzywon Was there a reason not to merge this? Feel like there might have been, but it's been here a while.
> > 
> > 
> > I thought someone should review the content of the text before merging, otherwise, no.
> 
> Unless its factually incorrect, it looks fine.

The factual correctness is what I want someone to review.

**Comment by lucas-wilkins** [comment]
1) Is there anyone other than @dehoni, the author, that's in a position to
do that?
2) If there is, what's the chance that they actually will do it?

**Review by smk78 — APPROVED** [review]
Descriptions look fine to me.

**Pull request merged**
