### PR TITLE
Scattering calculator docs

### PR DESCRIPTION
**Pull request by dehoni**
After the changes to the generic scattering calculator with the PRs #1888 #1898 and #1899, the user documentation needs to be updated. Once all these are merged the documentation PR should be reviewed and updated.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
@dehoni can you help me resolving the conflict, please?

**Comment by dehoni** [comment]
> @dehoni can you help me resolving the conflict, please?

The image files are not used anymore since the equation are now generated directly from the rst file sas_calculator_help.

**Comment by wpotrzebowski** [comment]
@dehoni thanks!  
Sorry, I am bit confused. Did someone review this PR?

**Comment by dehoni** [comment]
Artem Feoktystov had a play with the documentation. His comments are found in the linked issue: https://github.com/SasView/sasview/issues/1918#issuecomment-956138686

**Pull request merged**
