### PR TITLE
2903: Fix for the iPython console in Windows

### LINKED ISSUE #2903: Python console isn't working in new beta
**Describe the bug**
In the 6.0.0 Beta, the python shell/editor isn't able to open. An error code "ERROR: Traceback (most recent call last): File "sas\qtgui\MainWindow\GuiManager.py", line 1055, in actionPython_Shell_Editor File "sas\qtgui\Utilities\IPythonWidget.py", line 36, in __init__ File "qtconsole\base_frontend_mixin.py", line 64, in kernel_client File "qtconsole\jupyter_widget.py", line 323, in _started_channels File "ipykernel\inprocess\client.py", line 160, in kernel_info File "ipykernel\inprocess\client.py", line 195, in _dispatch_to_kernel File "jupyter_core\utils\__init__.py", line 165, in wrapped File "asyncio\base_events.py", line 654, in run_until_complete File "ipykernel\kernelbase.py", line 449, in dispatch_shell AttributeError: 'NoneType' object has no attribute 'flush'"

Theorized to be due to the new cli.py file created for 6.0.0 beta, cli.py is the one that sets up console + passes args (which would then return None).

**To Reproduce**
1. Go to tools
2. Click on Python Shell/Editor
3. See error

**Expected behavior**
Should open up the jupyter widget as a side panel.

**Screenshots**
image

**SasView version (please complete the following information):**
 - Version: 6.0.0b1

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by krzywon**
## Description

This fixes the issue related to the the iPython console throwing an error when attempting to open it when running from the Windows installer. This also fixes an issue related to the logging where a variable did not exist.

Fixes #2903

## How Has This Been Tested?

I downloaded and installed the installer. The console worked.

## Review Checklist:

**Documentation** (check at least one)
- [x] There is **nothing** that needs documenting
- [ ] Documentation changes are **in this PR**
- [ ] There is an **issue** open for the documentation (link?)

**Installers**
- [x] There is a chance this will affect the **installers**, if so
  - [ ] **Windows** installer (GH artifact) has been tested (installed and worked) 
  - [ ] **MacOSX** installer (GH artifact) has been tested (installed and worked)

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by lucas-wilkins — COMMENTED** [review]
Doesn't look like it will break anything. Can't check it fixes anything, as I couldn't reproduce the bug on my machine.

**Comment by rozyczko** [comment]
works for me. I did see the issue with previous builds so the PR fixes it.
However, the console is still visible for the whole lifetime of the sasview process. Should it not be hidden?

**Comment by krzywon** [comment]
> works for me. I did see the issue with previous builds so the PR fixes it. However, the console is still visible for the whole lifetime of the sasview process. Should it not be hidden?

Are you on Windows 11? https://github.com/pyinstaller/pyinstaller/issues/8022

**Comment by rozyczko** [comment]
> > works for me. I did see the issue with previous builds so the PR fixes it. However, the console is still visible for the whole lifetime of the sasview process. Should it not be hidden?
> 
> Are you on Windows 11? [pyinstaller/pyinstaller#8022](https://github.com/pyinstaller/pyinstaller/issues/8022)

Makes sense now. The same installer on another machine with Windows 10 works as expected.

**Comment by wpotrzebowski** [comment]
Tested if it doesn't break Mac. It works ok. I think it is ready to be merged

**Review by butlerpd — APPROVED** [review]
Just downloaded windows installer which works as advertized with windows 10 - for a test I ran `check_model` on `fcc_paracrystal` which showed that the unit tests pass.

Given that it has essentially been vetted and approved for mac and PC already by @rozyczko and @wpotrzebowski I'm approving and merging

**Pull request merged**
