### PR TITLE
Doc Update: P Scaling

### PR DESCRIPTION
**Pull request by smk78**
This PR is one of two addressing https://github.com/SasView/sasview/issues/1708. The other being https://github.com/SasView/sasmodels/pull/487.

A retrospective comment has been added under 'New in 5.0.4' to RELEASE.rst.

Mention also needs to be made somewhere in the SasView Help docs.

### CODE REVIEW

**Comment by pkienzle** [comment]
https://github.com/SasView/sasmodels/pull/487#discussion_r742269072 applies here as well.

**Comment by smk78** [comment]
Have changed comment in RELEASE.rst to read:

image

**Comment by smk78** [comment]
The following note has also been added at the bottom of the Interaction Models section in fitting_help.rst:

image

**Review by pkienzle — APPROVED** [review]

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Pull request merged**
