### PR TITLE
Fixes to invariant plot high q extrapolation

### LINKED ISSUE #1749: Invariant not extrapolating over listed high-q
The invariant perspective does not extrapolate over the entire high-q range listed in the GUI (default 10 Angstrom<sup>-1</sup>). The total number of points in the extrapolated data is always 500. The low-q extrapolation goes to the expected low-q value, but often using fewer points.

Example: load test\1d_data\AOT_Microemulsion-Drop_Contrast.xml into the the invariant perspective, with the extrapolation limit at the default and the extrapolation ends at 0.843 Angstrom<sup>-1</sup> over 500 points.

This issue has been present since at least release v4.2.2.

More comments and examples can be found in PR #1718.

### PR DESCRIPTION
**Pull request by phgilbert**
Removes 3x upper limit on invariant high Q extrapolation plot, and replaces with user defined upper q limit.

Fixes #1749 (High Q Part)

### CODE REVIEW

**Comment by butlerpd** [comment]
ready for testing on Win

**Review by rozyczko — COMMENTED** [review]
Code looks good, would be useful to add a unit test for this change.
Do the current unit tests pass?

**Review by krzywon — APPROVED** [review]
I don't see a way to make the test I suggested work without completely reworking `InvariantPerspectiveTest.py`.

I suggest we merge this as-is and I'll ticket the issue for the invariant tests.

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Pull request merged**
