### PR TITLE
List of Contributors

### PR DESCRIPTION
**Pull request by lucas-wilkins**
I've started a relatively machine readable list of contributors. `build_tools/contributors.tsv'

I have just gone with the contributor, producer and related person categories for now, as I think that makes things much simpler (working definitions in the file). I've done my very best to offend as many people as possible.

I had no idea who some of the people were, and there were even more where I wasn't sure what they've done, so there's some question marks and empty spaces. Perhaps @butlerpd can look through it and fill in the missing parts.

(I know its against main, I'll fix that later)

### CODE REVIEW

**Comment by andyfaff** [comment]
Is this a list of contributors to v6 only, or contributors to sasview over several versions? 
How is it measured? By having committed code? What's in this list doesn't reflect all the people in the latter category.

**Comment by lucas-wilkins** [comment]
> Is this a list of contributors to v6 only, or contributors to sasview over several versions? 

I wrote this in the file with the names, but yes.

> How is it measured? By having committed code? 

Depends on the category, but yes, or the other kinds of contribution listed

> What's in this list doesn't reflect all the people in the latter category.

Who's missing (other than the names I added to this issue)? Pretty hard to fix it if you don't say who.

**Comment by andyfaff** [comment]
My name for one 😉, Andrew Nelson. It should be fairly easy to write a script that scrapes the repo for commit names and emails.

**Comment by lucas-wilkins** [comment]
OK, thought you would have been on the 5.0.x lists. Seems you're not.

**Comment by smk78** [comment]
> OK, thought you would have been on the 5.0.x lists. Seems you're not.

Interesting. This is an example of why I said we needed to look at this carefully. @andyfaff _is_ named on the website (https://www.sasview.org/people/) as a developer/contributor and has been for some time.

**Comment by lucas-wilkins** [comment]
> > OK, thought you would have been on the 5.0.x lists. Seems you're not.
> 
> Interesting. This is an example of why I said we needed to look at this carefully. @andyfaff _is_ named on the website (https://www.sasview.org/people/) as a developer/contributor and has been for some time.

Yeah, we need to have a meeting just about this I think. But try to gather as many names as possible before hand.

**Comment by lucas-wilkins** [comment]
Names to fix: Annika Stellhorn
Affilations: Drew Parsons, U Cagliari

**Comment by krzywon** [comment]
> Names to fix: Annika Stellhorn Affilations: Drew Parsons, U Cagliari

Done plus others

**Comment by smk78** [comment]
I notice some fields have quotes around them and others don't, is this important?

**Comment by butlerpd** [comment]
@lucas-wilkins can we close this PR now and delete the branch? As agreed I moved the file to release_6.0.0 and about to merge it (should be before you see this ... I think?)

**Comment by lucas-wilkins** [comment]
@butlerpd if you've copied the file over, just close this PR. Don't forget about the related issue.

**Comment by krzywon** [comment]
As noted by @butlerpd, the work here is already in release_6.0.0, so it will be brought back to main at some point. Closing this for now, but I won't delete the branch.

**Pull request closed without merging**
