### PR TITLE
TST: Lxml dependencies

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Removed requirements.txt. Conda ymls has been updated. Works on notarization machine too but with lxml=4.3.0. 
Anyway I suggest to merge it because it also has fixes to make regular builds to run again (Pillow dependency).

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Windows

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Review by rozyczko — APPROVED** [review]
Looks good.
One minor question is limiting versioning for `bumps` on Linux - should we not just use the latest version? I don't think there are any API breaking changes happening,

**Comment by wpotrzebowski** [comment]
> Looks good.
> One minor question is limiting versioning for `bumps` on Linux - should we not just use the latest version? I don't think there are any API breaking changes happening,

Yes, I agree with bumps. I don't know if there was a particular reason to fix it but it seems to work with latest release. I will fix it and merge

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Pull request merged**
