### PR TITLE
Removed and moved multiple .spec files

### PR DESCRIPTION
**Pull request by lucas-wilkins**

### CODE REVIEW

**Review by rozyczko — COMMENTED** [review]
you removed `sasview.spec` entirely?

**Comment by wpotrzebowski** [comment]
> you removed `sasview.spec` entirely?

I think it is the one in build_tools and we have another one in installers?

**Comment by rozyczko** [comment]
> > you removed `sasview.spec` entirely?
> 
> I think it is the one in build_tools and we have another one in installers?

Ah! Ok, I just looked at the changes and assumed this was the only occurrence of that file.

**Comment by lucas-wilkins** [comment]
Yeah, it was an old one that built version 4

**Review by rprospero — APPROVED** [review]
These spec files haven't been kept up to date.  Even if they were needed, someone would be better off modifying the main spec file than trying to update these files.

**Pull request merged**
