### PR TITLE
Use version parsing package for MPL version check

### PR DESCRIPTION
**Pull request by krzywon**
This uses a version parsing package bundled with setuptools (no extra dependencies) to help fix the 'nonposy' issue in MPL version > 3.3 that is used for the Github actions build.

### CODE REVIEW

**Comment by krzywon** [comment]
I realize `main` is already working in this regard, but this will help future proof the change, just in case this temporary solution isn't so temporary.

`version.parse("10.0.0") > version.parse("9.9.9")`

*but* 

`"10.0.0" < "9.9.9"`

**Review by rozyczko — COMMENTED** [review]
Yes, this is a more flexible and likely more error-proof solution.
However, I don't see any other use of this module (`packaging`) and it isn't specified in the yml, at least not on windows.
I think this is a non-standard module so it would need to be added, if not already pulled by some other dependency.
Let me check the installer then.

**Comment by rozyczko** [comment]
ready for testing on Win

**Comment by krzywon** [comment]
The `packaging` module comes bundled with `setuptools` so no extra dependencies should be required.

**Comment by rozyczko** [comment]
Interesting. Installing `setuptools` with conda does indeed add `packaging` even though the list of modules listed for download/installation doesn't include it...
In any case, we seem to have this package installed.

**Review by rozyczko — APPROVED** [review]

**Pull request merged**
