### PR TITLE
Added vertical and horizontal scrollbars to the main canvas. #1543

### PR DESCRIPTION
**Pull request by rozyczko**
it's scrollable now!

### CODE REVIEW

**Comment by butlerpd** [comment]
From the screenshot this looks like it would fix the corfunc issue as well. Can somebody test that? and then link that ticket?  ... though the auto closing does not seem to be working so well

**Comment by krzywon** [comment]
@butlerpd, I'll gladly test, but what corfunc issue are you referring to?

**Comment by butlerpd** [comment]
@krzywon - issue #1529 on Kanban board

**Comment by butlerpd** [comment]
5.0 ready for testing on Win

**Comment by krzywon** [comment]
All perspectives can be scrolled vertically and horizontally. Here is an image of the Corfunc perspective, with scroll bars, so this should also fix #1529.

sasview_5x_corfunc_with_scrollbars

**Comment by butlerpd** [comment]
cool. @smk78, can we now close this ticket as well?

**Comment by smk78** [comment]
Yes! Close https://github.com/SasView/sasview/issues/1529 too!

**Comment by pkienzle** [comment]
The main window scrolling works on mac.

However, there is conflict between scrolling the main canvas and scrolling within a window on the canvas.  With the trackpad motion, some mouse wheel events are given to the main canvas and some are given to the window under the mouse pointer. With plot windows the result is a graph that is so badly zoomed that you can't tell where the data is. It would be best to ignore wheel events on the window unless that window is selected. Maybe need a way to unselect a window to enable scrolling the canvas when the window is large.

Some weird interactions between scrolling and maximizing. May want to eat all events generated between maximize start and maximize complete.  The result is only glitchy, not unusable.  There is occasional glitchiness between maximize, scrolling and arrow keys as well.

**Comment by rozyczko** [comment]
As discussed during the call, I modified the scrollbars to be always visible in a bid to help with functionality.

**Comment by pkienzle** [comment]
The request to show/hide scroll bars is ignored on the mac.  They are visible if you have "Show scroll bars: Always" turned on in the General Systems Preferences, but only appear when scrolling otherwise.  I don't think this is a battle worth fighting.

If it is easy to suspend scroll wheel zoom in the plots, and instead feed the events to the underlying canvas, that might still be useful.

**Comment by krzywon** [comment]
Would adding the following to PlotterBase.py help with @pkienzle's suggestion?
`def wheelEvent(self, event): event.ignore()`

Where I found the idea:
https://doc.qt.io/qt-5/qwidget.html#wheelEvent

In regards to the scroll bars, always showing them detracts more than it adds, in my opinion.

**Comment by RichardHeenan** [comment]
Tried this branch, local build on Win10, great step forward in use of screen real estate.

(If I drag vertical scroll bar in a FitPage, then mouse wheel will move that scroll until it gets to end of travel, then the main canvas moves, but that is fine once you realise what is going on.)

**Comment by butlerpd** [comment]
Sounds like we can merge this PR - but waiting for response from Piotr on @krzywon suggestion. Would it be better? would it be a trivial change here? if yes to both is it something that should be in a new ticket rather than tackle here?

Unless it really is trivial and obviously a much better solution I would vote we get this out as is for 5.0.3 and put the suggested change as a future issue to consider.

**Comment by rozyczko** [comment]
> Would adding the following to PlotterBase.py help with @pkienzle's suggestion?
> `def wheelEvent(self, event): event.ignore()`

We probably don't want to remove wheel events from plots. These events are used for zooming control. Admittedly, we can now zoom with actual MPL zoom tool in the MPL toolbar, so removing this functionality might have some merit.

**Comment by pkienzle** [comment]
The other question is whether the permanent scrollbar are a net benefit.  I side with @krzywon on this one, and have them turned off until needed on Mac. I suggest reverting the last commit (or not) and merging.

**Comment by RichardHeenan** [comment]
On Windows we need the scroll bars as corfunc is unusable on average size screen, and many more perspectives are unusable on smaller screens and via other interfaces.  We all also gain much more real estate to park all those polydispersity and residuals plots that keep popping up even if you have minimised them.

**Comment by rozyczko** [comment]
@RichardHeenan I don't think the issue is with the scrollbars themselves. They stay. What PK and JK argue is whether we need the scrollbars always present on the canvas as opposed to present only when there is hidden content in widgets displayed on the canvas.

I tend to agree with them and show them (automatically) only when needed. That is, only when a widget (perspective, chart, plot etc) requires it.

**Pull request merged**
