### PR TITLE
Fix image filename in docs

### PR DESCRIPTION
**Pull request by llimeht**
Image file was renamed but the rst was not updated.

### CODE REVIEW

**Comment by butlerpd** [comment]
This looks to be new documentation for 5.x? Or was 4.x using extracting docs from bumps and 5.x is duplicating?

**Comment by pkienzle** [comment]
Yes, qtgui docs.  The PR is against ESS_GUI.

**Comment by llimeht** [comment]
Alternative patch (rebased onto current ESS_GUI HEAD) which renames the image file instead.

(I'm not sure I understand the duplication of the documentation between bumps and sasview.)

**Comment by pkienzle** [comment]
The docs were copied to Qt because the bumps docs use screen shots from the bumps wx panels for the docs, not the qt panels that are implemented in the ESS GUI.

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on OSX

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on Win

**Pull request merged**
