### PR TITLE
minor change to sas_gen.py which should fix #1886

### LINKED ISSUE #1886: The 'Save SLD Data' button in the generic scattering calculator saves sld data with rows and columns flipped
When saving loaded data in the generic scattering calculator as a .sld file the rows and columns of the data are saved the wrong way around. e.g. the initial file:
```
X  Y  Z  SLDN  SLDMx  SLDMy  SLDMz
11 12 13 14 15 16 17 18
21 22 23 24 25 26 27 28
```
would be resaved by the calculator as:
```
X  Y  Z  SLDN SLDMx  SLDMy  SLDMz VOLUMEpix
1.100000000000000000e+01 2.100000000000000000e+01
1.200000000000000000e+01 2.200000000000000000e+01
1.300000000000000000e+01 2.300000000000000000e+01
1.400000000000000000e+01 2.400000000000000000e+01
1.500000000000000000e+01 2.500000000000000000e+01
1.600000000000000000e+01 2.600000000000000000e+01
1.700000000000000000e+01 2.700000000000000000e+01
1.800000000000000000e+01 2.800000000000000000e+01
```
As a result the new .sld files cannot be reloaded by the calculator.

### PR DESCRIPTION
**Pull request by rjbourne**
Use np.column_stack() to correctly arrange the outputted data for the sld file, so that it is in the correct order.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Review by wpotrzebowski — COMMENTED** [review]
`column_stack` looks like more logical choice here. Does it mean it was giving incorrect output before? It would be great if you can add unit test for this fix. You can take a look on what's been available here https://github.com/SasView/sasview/tree/main/test/sascalculator

P.S. Ignore failing OSX PR builder. There is unrelated problem with this build

**Comment by rjbourne** [comment]
Yes - the previous output had its rows and columns swapped, which meant that Sasview recognized it an an invalid file type and rejected it. Interestingly when the file is rejected Sasview throws a runtime exception which means that to the user it simply appears as if the file is still loading. It would probably be better for the error to be shown in the log and the loading visibly stopped so the user can see there is a failure rather than the file appearing to never load.

I can definitely add in a unit test, it should be fairly easy to save a small datafile and confirm that everything is stored as expected

**Review by wpotrzebowski — APPROVED** [review]

**Pull request merged**
