### PR TITLE
2133 resize and and rearrange corfunc panel

### PR DESCRIPTION
**Pull request by lucas-wilkins**
I've done some rearranging of the CorFunc panel to make it more compact.

@smk78 and @rozyczko - I would like your opinion

I also have an outstanding bug that I'm struggling with. The left hand part seems to load at a strange size on my machine. I'm on my week off now, so I thought I'd get this PR up and give you some time to look at it, despite this issue.

The issue is this: In Qt Designer its has a fixed horizontal size and looks like this:

image

But when I load it it looks like this

image

Note: the fixedness of the size doesn't change, just the size it gets fixed to. Any thoughts on what's happening would be appreciated.

### CODE REVIEW

**Comment by smk78** [comment]
Running this branch on W10/x64 I get this console message as the SasView starts:
```
(dev) D:\SasViewDevelopment\sasview-pr2135>python run.py
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
```
Then, when it does start the screen looks like this (on a 1680x1050 monitor):
image
Is it possible the Qt error is related to the weird scaling?
In any event, I don't see why I should be expected to use the lateral scroll to use the Corfunc perspective on a widescreen monitor.

**Review by smk78 — APPROVED** [review]
I do, however, like this layout more than the previous!

- As commented on https://github.com/SasView/sasview/pull/2132, I would much prefer to have draggable range bars on the Q-space plot, rather than the 'Adjust' bar;
- Could we display the experimental data as markers+error bars, rather than joined datapoints, please?;
- Could we have a third plot tab to display the IDF, please? This might require a change to the plot tab labels (since the IDF is also real space);
- I note that 'Save Extrapolated' writes a 2-column _CSV_ file whilst 'Save Transformed' writes a 4-column _space-delimited_ file with a Corfunc-specific extension: there should be some consistency! I would suggest we standardise on CSV for both for now (ideally, of course, we should also offer the transformed as CanSAS1D and NXcanSAS with separate SASdata blocks for the 1D, 3D & IDF);
- Could we add a 3rd column to Save Extrapolate - the intensity minus the background (ie, what is being transformed; at least, what I assume is being transformed???!!!) - please?;
- We need a way to save the Extracted Parameters to file (Edit > Save Params to File doesn't work), but I think this is/was a separate issue?

But overall, I give this PR qualified approval.

**Comment by lucas-wilkins** [comment]
> Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.

Hmmm, that might be something to look at in general, for all my weird Qt issues. e.g. #2043

**Comment by lucas-wilkins** [comment]
> As commented on https://github.com/SasView/sasview/pull/2132, I would much prefer to have draggable range bars on the Q-space plot, rather than the 'Adjust' bar;

In due time.

> Could we display the experimental data as markers+error bars, rather than joined datapoints, please?;

Please make feature request to this effect.

> Could we have a third plot tab to display the IDF, please? This might require a change to the plot tab labels (since the IDF is also real space);

Isn't this already a feature request - #2107

> I note that 'Save Extrapolated' writes a 2-column CSV file whilst 'Save Transformed' writes a 4-column space-delimited file with a Corfunc-specific extension: there should be some consistency! I would suggest we standardise on CSV for both for now (ideally, of course, we should also offer the transformed as CanSAS1D and NXcanSAS with separate SASdata blocks for the 1D, 3D & IDF);

Feature request

> Could we add a 3rd column to Save Extrapolate - the intensity minus the background (ie, what is being transformed; at least, what I assume is being transformed???!!!) - please?;

Sounds like you want to open a new feature request ;)

> We need a way to save the Extracted Parameters to file (Edit > Save Params to File doesn't work), but I think this is/was a separate issue?

I've been working on this. #2103 - Same underlying functionality, work on this stalled because I needed to chat with people about it and I started on other bits instead.

**Pull request merged**
