### PR TITLE
Ticket 1727 lxml

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Upgrading lxml package with potential security vulnerability

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
It would be good if someone checks if Windows installer: https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/69/. I've tested OSX and Linux.

**Review by llimeht — APPROVED** [review]
SasView has been using python3-lxml 4.6.2 in Debian for a while. Looks fine to me.

**Comment by butlerpd** [comment]
presumably you need testing whatever uses the lxml library right? I'm not sure I know what uses that? ... in other words what part is  in most need of testing

**Comment by krzywon** [comment]
The lxml library is used in the cansasXML reader.  I'll run an independent check locally, but if the sascalc unit tests run by the github actions are passing (which they appear to be), this should be okay to merge.

**Review by butlerpd — APPROVED** [review]
windows build runs and loads canSASxml test data as well as an old cvs project file (which I think was xml based?)  so good to merge.

**Pull request merged**
