### PR TITLE
Close theory plots on theory deletion

### LINKED ISSUE #1754: Delete Data does not remove data or plots from Fitting, P(r) or Inversion
Pulled and built 5x main on W10 to test #1742 (verifying @butler 's observations) on the P(r) perspective. But then, with the data still checked in the data explorer I selected Delate Data. The confirmation box appeared warning that all data and dependent datasets would be deleted, but on confirming 'yes' nothing happened! The data and plots persist!

The console reports:
```
17:42:39 - ERROR: Traceback (most recent call last):
  File "D:\SasViewCodeDev\sasview-qt5\src\sas\qtgui\MainWindow\DataExplorer.py", line 695, in deleteFile
    self.closePlotsForItem(item)
  File "D:\SasViewCodeDev\sasview-qt5\src\sas\qtgui\MainWindow\DataExplorer.py", line 1821, in closePlotsForItem
    current_plot_items[plot_name] = PlotHelper.plotById(plot_name).item
AttributeError: 'PlotterWidget' object has no attribute 'item'
```
Checking the Inversion and Fitting perspectives I find the same thing.

Moreover, having first created plots with P(r) and then Inversion, when I then sent a third dataset to Fitting and did Show Plot, only the chosen model function appeared, the experimental data did not display. Only when I manually closed all the open plots and then did Show Plot again could I get the normal data + model plot.

### PR DESCRIPTION
**Pull request by krzywon**
Theory plots are now closed when theory data is deleted.

Fixes #1754 (last remaining issue related to the ticket)

### CODE REVIEW

**Review by rozyczko — APPROVED** [review]
Now THAT was a low hanging fruit...

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by butlerpd** [comment]
ready for testing on Win

**Review by butlerpd — APPROVED** [review]
does what it says it should do now and now obvious (from a very quick scan) new artifacts introduced.  From the one line change it is hard to see any other consequences.

I will note however that checking only a "subdataset" and clicking delete does nothing but throws some errors. However right clicking and selecting delete does the correct thing of removing the sub item and the plot associated with the subitem.  This should probably be ticketed for 5.0.5 of 5.1.

**Pull request merged**
