### PR TITLE
ESS_GUI: silence matplotlib debug/info warnings in log files

### PR DESCRIPTION
**Pull request by pkienzle**

### CODE REVIEW

**Comment by pkienzle** [comment]
76000 out of 82000 lines in my sasview.log contain matplotlib.

**Comment by rozyczko** [comment]
Maybe by chance you have `FILTER_DEBUG_LOGS` set to `False` in your `custom_config.py`?
By default it should filter MPL silliness and it's set to `True`

**Comment by pkienzle** [comment]
It is set to `True`.  

Regardless, when I turn on debug mode for sasview/sasmodels I don't want to be flooded with MPL stuff, so the PR still stands.

**Comment by rozyczko** [comment]
fine

**Pull request merged**
