### PR TITLE
Ess gui test ipython

### PR DESCRIPTION
**Pull request by rozyczko**
Modified dependencies and code to re-enable python console for Windows.

### CODE REVIEW

**Comment by rozyczko** [comment]
5.0 ready for testing on Win64

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on OSX

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on OSX

**Pull request merged**
