### PR TITLE
Allow setting checkbox state on item selection in DataManager. #1699

### PR DESCRIPTION
**Pull request by rozyczko**

### CODE REVIEW

**Review by smk78 — APPROVED** [review]
I've not reviewed the code, but have done a functionality test building the branch locally on W10/x64.

It works as expected.

It is ever so slightly unintuitive, in that having selected your data sets by shift-click or ctrl-click you then have to realise you need to check a box for any selected data set in order for it to check them all (I initially right-clicked looking for a 'select' on the context menu).

**Comment by rozyczko** [comment]
> I initially right-clicked looking for a 'select' on the context menu).

Yes, this functionality should be available also from the right click menu. 
Added in the most recent commit.

**Comment by smk78** [comment]
Pulled and tested latest commit.
The context menu now shows 'Select'/'Unselect' options and these do do something with the checkboxes of any selected data sets.
_However_ when you choose 'Select' what it does is turn the checkbox from an outline square to a filled-in square. Whereas, when you select data sets individually the checkbox gets ticked.
What I see is that SasView will only action data sets that are ticked, not those with filled-in squares!!!

**Comment by rozyczko** [comment]
> What I see is that SasView will only action data sets that are ticked, not those with filled-in squares!!!

Thanks. This is fixed now and the code got simplified in the process.

**Comment by smk78** [comment]
Pulled and tested latest commit.
Glitch is now fixed!

**Comment by butlerpd** [comment]
Do we know why Travis is barfing here? otherwise I guess we can merge?

**Comment by rozyczko** [comment]
Looks like a random fluke? Let's try on Jenkins.

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
Right, succeeded on Jenkins, so most likely a random barf.

**Pull request merged**
