### PR TITLE
Gsc log spacing

### LINKED ISSUE #2537: Log spacing for Generic Scattering Calculator
**Is your feature request related to a problem? Please describe.**
The Generic Scattering Calculator currently evaluates Q-Bins with Linear Spacing, despite being plotted on a Log scale. Furthermore, there is no option for the user to choose the minimum Q -  The minimum Q is just automatically set to the Q-Max * .001.

**Describe the solution you'd like**
Adding the option for Log Spacing as well as a Minimum Q input.

**Additional context**
Custom Plugin Models from Generic Scattering Calculator will use a Log Spacing .

### PR DESCRIPTION
**Pull request by smalex-z**
## Description

Fixes Issue #2537 where Log Spacing and Q-Minimum was unavailable to any users in the Generic Scattering Calculator. Now, an extra Input box and a checkbox has been added to let the user add their own Qx-Minimum values and choose whether they want to use Linear or Log Spacing. This feature is only available for 1D scattering: 2D scattering assumes the detector in the center, so Qx Minimum is set to negative QxMax, and 2D Scattering only uses Linear Spacing, not Log Spacing.

The python math class is now imported with this PR.

NOTE: Do not merge this PR with main, only approve it. Due to merging issues with the UI files, PR #2538, #2548, and an upcoming PR will be merged to main together when all 3 are approved.

Fixes #2537 

## How Has This Been Tested?

- Upload Nuclear Data into GSC
- Qx Min should be set to (QMax * -1) and Box should be disabled
- Log Spacing Box should be unchecked and disabled
- If Dropdown is changed to Debye Full Average:
- Qx Min should be set to (QMax * .001) and Box should be Enabled
- Log Spacing Box should be checked and Enabled

Upon calculation of BetaQ and Form Factor, both should follow either Linear or Log Spacing (based off User selection). 

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by krzywon — COMMENTED** [review]
There are a few issues I'd prefer to see fixed, and I'll stop by to discuss linearizing the entire beta calculation.

**Comment by butlerpd** [comment]
Looks like there remain unaddressed comments? Or does that last commit actually resolve everything?

**Comment by smalex-z** [comment]
Not yet- I wasn't able to discuss with Jeff until the end of the day on Friday so I'll handle it on Monday morning.

**Comment by dehoni** [comment]
Maybe think about changing position of qmin first and qmax below, to keep order.
I have tested the new feature. qmin is working for linear data and log data. The produced data at the end points (qmin, qmax) are overlapping nicely.
When user sets qmin larger than qmax, box is highlighted in yellow. The result look identical, as it does simply swap values.

**Comment by smalex-z** [comment]
Calculation has been linearized slightly, and the validator has now been changed to block 0 but still allowing the user to type in decimals (0.5) but not calculate with invalid numbers. Previously, users were barred from typing invalid numbers or symbols entirely (-, 1000+,'.',etc). Now the user can still type them, just unable to hit the compute it. This change was taken so the user can still type decimals (0.5) without being barred from typing the 0 first.

**Comment by smalex-z** [comment]
Wrong Issue/PR tagged & closed - #2538 accidentally tagged instead of #2539.

**Comment by butlerpd** [comment]
This pull request and #2548 should be reviewed and hopefully approved but should d to wait be merged into one big pull request to resolve all the UI conflict and that pull request then merged. To avoid confusion I'm labeling this as WIP

**Comment by butlerpd** [comment]
Once Jeff approves this we need to close the PR as the changes have been munged into PR #2565.  This PR should NOT be merged

**Comment by pkienzle** [comment]
Similar changes in #2565 and #2548. It would be easier to handle review and merge if you have a single PR.

**Comment by butlerpd** [comment]
@krzywon can we delete this branch now? If I remember right these changes were merged into another PR and the big PR then merged?

**Comment by krzywon** [comment]
This PR and #2548 are both included in #2565, the Custom Fit Models PR, which is still a WIP. The two branches can probably be deleted, but the work is still not merged into any protected branch at this point.

**Pull request closed without merging**
