### PR TITLE
Update reader and writer for NXcanSAS v1.1 changes (v5.x)

### PR DESCRIPTION
**Pull request by krzywon**
This is a parallel PR for #1530 pointing to the ESS_GUI branch instead of master.

refs #1527

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on OSX

**Comment by smk78** [comment]
Pulled this branch also, built and ran locally on W10/x64. Read & displayed existing v1.0 NXcanSAS .h5 files ok. Wrote out, read back in & displayed .h5 files from the graph windows (would these have been tagged v1.1?). Used the File Converter to convert a dataset to .h5 (would this also have been tagged v1.1?), read that back in and displayed it. So nothing in this PR breaks existing functionality with NXcanSAS. Was obviously unable to test loading of an externally produced v1.1 file as no one is yet producing them!

**Comment by smk78** [comment]
Files written from this branch build also read back in to release version.

**Comment by krzywon** [comment]
5.0 ready for testing on Win64

**Comment by krzywon** [comment]
5.0 ready for testing on Win

**Comment by smk78** [comment]
Tested Win10 PR build #32: https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/32/ . The eccentricity* I was encountering on my local build _is not_ present. So I have no idea what was going on! 

*basically if I loaded a CanSAS1D .xml file, _two_ instances would appear in the Data Explorer, but only one of them contained plottable data! @krzywon was totally unable to reproduce this behaviour, and I could not reproduce it in any other locally built 5x branch, though I _could_ reproduce it in the 4x branch (https://github.com/SasView/sasview/pull/1530) linked to this PR.

**Pull request merged**
