### PR TITLE
Tutorials open in browser to avoid PDF failure

### LINKED ISSUE #2908: Links in tutorial.rst don't resolve
**Describe the bug**
The links in tutorial.rst from Help > Tutorial don't resolve.

However, https://github.com/SasView/tutorials/pull/15 and https://github.com/SasView/tutorials/pull/14 also need merging and this will change the suffix of some of the filenames to _v6.

### PR DESCRIPTION
**Pull request by lucas-wilkins**
The links to tutorials from the document editor don't work because they're PDF files, and it can't open them

I've changed the tutorial opening behaviour to back to just opening a web link as it did before.

I've opened an issue for updating the editor to handle PDFs - #2926 

fixes #2908

### CODE REVIEW

**Review by smk78 — COMMENTED** [review]
Tested actions/runs/9758139744 on W10/x64.

Help > Tutorials does spawn a new window in the default browser but the links still do not open (but do work if you copy/paste them into a browser tab or file explorer).

Help > Documentation > User Documentation > Working with SasView > Tutorials still uses the Documentation Viewer and again the links do not open.

I have tried clearing my browser (Chrome) cache and even resetting. Made no difference.

Others should see what behaviour they get on different platforms/browsers.

**Comment by butlerpd** [comment]
problem if one tries to link to pdf from the documentation itself. Maybe remove from documentation itself? Needs some testing? @smk78 and @lucas-wilkins to discuss. Others should try installer.

**Review by smk78 — APPROVED** [review]
Tested actions build 9765628806 on W10/x64

Help > Tutorials now opens a browser page at https://www.sasview.org/docs/user/tutorial.html and so the links now work.

A separate PR will need to address the route by Help > Documentation > User Documentation > Working with SasView > Tutorials

**Comment by lucas-wilkins** [comment]
@smk78 That link hasn't been removed has it?

**Comment by smk78** [comment]
I'm dealing with them now in https://github.com/SasView/sasview/tree/2926-Fix-broken-tutorial-links-in-Working-with-SasView

**Pull request merged**
