### PR TITLE
Remove UI conversion from run.py

### LINKED ISSUE #2510: Run.py no longer launches
**Describe the bug**
For environments where your current working directory of SasView is **not** part of the python path, the changes in PR #2483 now cause an error when running `run.py`. Anyone following the directions exactly as stated at https://github.com/SasView/sasview/wiki/DevNotes_CondaDevEnviroment will end up with this error.

Error: 
> Traceback (most recent call last):
  File "sasview\run.py", line 88, in <module>
    rebuild_new_ui()
  File ".conda\envs\sasview-dev\lib\site-packages\sas\qtgui\convertUI.py", line 79, in rebuild_new_ui
    if force or file_in_newer(in_file, out_file):
  File ".conda\envs\sasview-dev\lib\site-packages\sas\qtgui\convertUI.py", line 53, in file_in_newer
    in_stat = os.stat(file_in)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.conda\\envs\\sasview-dev\\lib\\site-packages\\sas\\qtgui\\UI\\main_resources.qrc'

**SasView version (please complete the following information):**
 - Branch: main

**Additional context**
Workarounds for now:
1. Comment out lines 87 and 88 in run.py.
2. Add the sasview working directory to the python path.

### PR DESCRIPTION
**Pull request by krzywon**
## Description

This removes the UI generation step to ensure all environments are able to start the SasView application using `run.py`.

Fixes #2510

## How Has This Been Tested?

Ran `python run.py` from the base sasview directory and the application launched.

## Review Checklist (please remove items if they don't apply):

- [x] Code has been reviewed
- [ ] Functionality has been tested

### CODE REVIEW

**Comment by lucas-wilkins** [comment]
I added that in because the UI wasn't rebuilding when you run from run.py like it did before you made your changes. Looking at this change I suspect this will break it again.

**Comment by lucas-wilkins** [comment]
Oh yeah, sorry, someone else broke it.

**Comment by lucas-wilkins** [comment]
I would suggest fixing it instead of hacking it though.

**Comment by krzywon** [comment]
I'll see what I can do here, but I think removing this from run.py (it can still be run through setup.py) will have an immediate impact.

**Comment by lucas-wilkins** [comment]
It used to work!

**Comment by krzywon** [comment]
I'm not arguing it didn't, but adding it back in #2483 made things worse. An error is thrown regardless of how run.py is launched, making it impossible to run from the source. This helps solve the immediate issue. I suggest ticketing the other issue and I'll see if I can solve it here.

**Comment by lucas-wilkins** [comment]
If it breaks things for anyone and its on main then it needs to be fixed, I don't disagree. It ran perfectly fine for me, so I didn't see the issue when I committed it.

It's just annoying that a feature I use *a lot* has been unilaterally removed (not you, I know).

**Comment by lucas-wilkins** [comment]
As it works perfectly fine for me, its hard to test, but perhaps moving the `prepare()` call up will fix it:

i.e. like this:

```
    prepare()
    
    from sas.qtgui.convertUI import rebuild_new_ui
    rebuild_new_ui()

```

**Comment by krzywon** [comment]
Yeah, it was that easy.

**Comment by lucas-wilkins** [comment]
Excellent!

**Review by lucas-wilkins — APPROVED** [review]

**Review by caitwolf — APPROVED** [review]
I was getting the errors described in #2510 on my machine and so after testing I can confirm these changes fixed the bug.

**Pull request merged**
