### PR TITLE
2719, 2727, 2733: Documentation Editor Fixes

### LINKED ISSUE #2719: Plugin model documentation loading fails
**Describe the bug**
In the documentation editor, trying to load a plugin model file documentation throws an error.

**To Reproduce**
1. Open v6.0.0 alpha.
2. Select a plugin model in the fitting perspective.
3. Click 'Help' button.
4. Error is thrown.

**Expected behavior**
An rst file should be generated using the plugin model and the documentation editor should open with the rst file.

**SasView version (please complete the following information):**
 - Version: 6.0.0a

### LINKED ISSUE #2727: Merging local-document-generation branch broke SV
**Describe the bug**
PR #2576 merged `local-document-generation` into `develop`: https://github.com/SasView/sasview/commit/9e3698b16b02654b8e8a2865c2e3b4b2855f9d34

This causes issues when starting SV from the dev build

```
Traceback (most recent call last):
  File "c:\projects\sasview\run.py", line 94, in <module>
    sys.exit(sas.cli.main(logging="development"))
  File "C:\projects\sasview\src\sas\cli.py", line 161, in main
    run_sasview()
  File "C:\projects\sasview\src\sas\qtgui\MainWindow\MainWindow.py", line 106, in run_sasview
    mainwindow = MainSasViewWindow()
  File "C:\projects\sasview\src\sas\qtgui\MainWindow\MainWindow.py", line 42, in __init__
    from .GuiManager import GuiManager
  File "C:\projects\sasview\src\sas\qtgui\MainWindow\GuiManager.py", line 37, in <module>
    from sas.qtgui.Utilities.DocViewWidget import DocViewWindow
  File "C:\projects\sasview\src\sas\qtgui\Utilities\DocViewWidget.py", line 13, in <module>
    from sas.sascalc.doc_regen.makedocumentation import make_documentation, HELP_DIRECTORY_LOCATION, MAIN_PY_SRC, MAIN_DOC_SRC
  File "C:\projects\sasview\src\sas\sascalc\doc_regen\makedocumentation.py", line 65, in <module>
    def get_py(directory: Union[Path, os.path, str]) -> list[Union[Path, os.path, str]]:
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 277, in inner
    return func(*args, **kwds)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 354, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 466, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 466, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 166, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got <module 'ntpath' from 'C:\\Users\\piotrrozyczko\\.conda\\envs\\sasview\\lib\\ntpath.py'>.
```

@gonzalezma reports that manually creating a `build` folder in docs/sphinx-docs is required to be able to run SV now.

**SasView version (please complete the following information):**
 - Version: `release_6.0.0`

**Operating system (please complete the following information):**
 - OS: Win10

### LINKED ISSUE #2733: Documentation: Show Source -> Edit fails
**Describe the bug**
Attempting to edit the doc source view fails with

```
0:41:13 - ERROR: Traceback (most recent call last): File "sas\qtgui\Utilities\DocViewWidget.py", line 52, in onEdit IndexError: list index out of range
```

**To Reproduce**
1. Open a documentation page (any)
2. Click on This Page - `Show Source`
3. Click on `Edit`

**Expected behavior**
Maybe disable the Edit button on Source View?

**SasView version (please complete the following information):**
 - Version: `release_6.0.0` branch

**Operating system (please complete the following information):**
 - OS: Win10

### PR DESCRIPTION
**Pull request by krzywon**
## Description

Several issues related to the documentation editor are fixed with this pull request.

Fixes #2719 - Plugin model documentation is now built and displayed as expected.
Fixes #2727 - SasView now starts if the documentation has not been built, which was the underlying cause of the error.
Fixes #2733 - No longer seeing the index error.

## How Has This Been Tested?

Tested locally and tested the installer from the latest push.

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] Developers documentation is available and complete (if required)

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
Maybe I am not testing it properly or I am not patient enough but on Mac for #2719 and #2733 test I am getting bunch of empty screens. 

  
Screenshot 2024-01-28 at 22 19 29
Screenshot 2024-01-28 at 22 18 08

**Comment by wpotrzebowski** [comment]
I am testing from the installer.

**Comment by butlerpd** [comment]
I believe it still takes a long time to compile the docs, with the length of time varying depending on whether the docs were already built once and/or what docs are being changed? That would be a "known issue" and I believe there are some thoughts on how it can be alleviated. However, if this happens on model documentation or too frequently elsewhere, we may need to at least see about a progress bar?

**Comment by wpotrzebowski** [comment]
Hmm..., I don't think it works in my case. After a while, the documentation window turns grey but nothing happens (I've been running it for more than 30min).
Screenshot 2024-01-29 at 06 14 01

**Comment by krzywon** [comment]
@wpotrzebowski - The documentation window should never be empty, so that is an issue. The first time the regeneration process is run can take quite a while, but I've never seen it run for more than 5-10 minutes. I'll test it on my Mac when I get a chance.

**Comment by wpotrzebowski** [comment]
Tested it locally and it works fine, so it seems to be the mac installer issue.

**Comment by krzywon** [comment]
> Tested it locally and it works fine, so it seems to be the mac installer issue.

This seems very similar to a number of issues I'm finding related to bundling QWebEngineViewer using pyinstaller, but all of those issues relate to older versions of both pacakges. This will need more investigation.

**Comment by butlerpd** [comment]
I can do the functionality review but somebody else likely should look at the code?

**Review by butlerpd — APPROVED** [review]
Not sure about the mac issue but on window it is a DREAM!!! Really nice.  It does take a bit of time to compile each plugin documentation, but once it is done it is just there like any other model doc, **including** after exiting and restarting SasView! NICE! 

So the penalty for compiling is not that bad I guess. Still, we can probably make it even better if we compile all plugins whose documentation does not yet exist (and only those) at SasView startup (behind the scenes)? Basically it would only run the first time and whenever somebody downloads a model from the marketplace.

There are a number of other things I think we could do to make it smoother and avoid possible confusion for the user (currently, anytime they edit their model, say while debugging the code, sphinx is launched. but these would be the subject of another PR I think.

This still needs to work on macs I guess. Does it also need a code review?

**Pull request merged**
