### PR TITLE
pr: fix numba type error causing failures on linux

### PR DESCRIPTION
**Pull request by pkienzle**
See #1583

### CODE REVIEW

**Comment by pkienzle** [comment]
Note: it seems that this code is using left Riemann sum for integration. Any reason not to use better quadrature such as the midpoint rule or Simpson's rule?

**Comment by butlerpd** [comment]
I doubt the particular integration method matters that much.  I suspect the current code is copied from C code that was probably written by @mdoucet back in the "olden days" of 2006-2008?

**Comment by smk78** [comment]
Just tried to build and run this branch on W10/x64. Seems to build ok, but falls over when executing python run.py:
```
Generating code
Finished generating code

(qt5) D:\SasViewCodeDev\ticket1583-numba>python run.py
11:14:15 - DEBUG : __main__: 181: Starting SASVIEW in debug mode.
running build_ext
Traceback (most recent call last):
  File "setup.py", line 414, in <module>
    tests_require=['pytest'],
  File "D:\Anaconda3\envs\qt5\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda3\envs\qt5\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\envs\qt5\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\envs\qt5\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\qt5\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "D:\Anaconda3\envs\qt5\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Anaconda3\envs\qt5\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "D:\Anaconda3\envs\qt5\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\Anaconda3\envs\qt5\lib\site-packages\tinycc\distutils.py", line 107, in __init__
    self.dll_libraries = get_msvcr()
  File "D:\Anaconda3\envs\qt5\lib\site-packages\tinycc\distutils.py", line 61, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900
11:14:17 - INFO : sas.sasview.sasview: 196:  --- SasView session started ---
11:14:17 - INFO : sas.sasview.sasview: 198: Python: 3.6.7 (default, Jul  2 2019, 02:21:41) [MSC v.1900 64 bit (AMD64)]
11:14:18 - DEBUG : matplotlib: 409: $HOME=C:\Users\smk78
11:14:18 - DEBUG : matplotlib: 409: matplotlib data path D:\Anaconda3\envs\qt5\lib\site-packages\matplotlib\mpl-data
11:14:18 - DEBUG : matplotlib:1156: loaded rc file D:\Anaconda3\envs\qt5\lib\site-packages\matplotlib\mpl-data\matplotlibrc
11:14:18 - DEBUG : matplotlib:1879: matplotlib version 2.2.3
11:14:18 - DEBUG : matplotlib:1880: interactive is False
11:14:18 - DEBUG : matplotlib:1881: platform is win32
11:14:18 - DEBUG : matplotlib:1882: loaded modules: ['builtins', 'sys', '_frozen_importlib', '_imp', '_warnings', '_thread', '_weakref', '_frozen_importlib_external', '_io', 'marshal', 'nt', 'winreg', 'zipimport', 'encodings', 'codecs', '_codecs', 'encodings.aliases', 'encodings.utf_8', '_signal', '__main__', 'encodings.latin_1', 'io', 'abc', '_weakrefset', 'site', 'os', 'errno', 'stat', '_stat', 'ntpath', 'genericpath', 'os.path', '_collections_abc', '_sitebuiltins', 'sysconfig', '_bootlocale', '_locale', 'encodings.cp1252', 'types', 'functools', '_functools', 'collections', 'operator', '_operator', 'keyword', 'heapq', '_heapq', 'itertools', 'reprlib', '_collections', 'weakref', 'collections.abc', 'importlib', 'importlib._bootstrap', 'importlib._bootstrap_external', 'warnings', 'importlib.util', 'importlib.abc', 'importlib.machinery', 'contextlib', 'mpl_toolkits', 'sphinxcontrib', 'zope', '__future__', 'imp', 'tokenize', 're', 'enum', 'sre_compile', '_sre', 'sre_parse', 'sre_constants', 'copyreg', 'token', 'sas', 'sas.logger_config', 'logging', 'time', 'traceback', 'linecache', 'string', '_string', 'threading', 'atexit', 'logging.config', 'logging.handlers', 'socket', '_socket', 'selectors', 'math', 'select', 'pickle', 'struct', '_struct', '_compat_pickle', '_pickle', 'queue', 'socketserver', 'pkg_resources', 'zipfile', 'shutil', 'fnmatch', 'posixpath', 'zlib', 'bz2', '_compression', '_bz2', 'lzma', '_lzma', 'binascii', 'pkgutil', 'platform', 'subprocess', 'signal', 'msvcrt', '_winapi', 'plistlib', 'datetime', '_datetime', 'xml', 'xml.parsers', 'xml.parsers.expat', 'pyexpat.errors', 'pyexpat.model', 'pyexpat', 'xml.parsers.expat.model', 'xml.parsers.expat.errors', 'email', 'email.parser', 'email.feedparser', 'email.errors', 'email._policybase', 'email.header', 'email.quoprimime', 'email.base64mime', 'base64', 'email.charset', 'email.encoders', 'quopri', 'email.utils', 'random', 'hashlib', '_hashlib', '_blake2', '_sha3', 'bisect', '_bisect', '_random', 'urllib', 'urllib.parse', 'email._parseaddr', 'calendar', 'locale', 'tempfile', 'textwrap', 'inspect', 'ast', '_ast', 'dis', 'opcode', '_opcode', 'pkg_resources.extern', 'pkg_resources._vendor', 'pkg_resources.extern.six', 'pkg_resources._vendor.six', 'pkg_resources.extern.six.moves', 'pkg_resources._vendor.six.moves', 'pkg_resources.py31compat', 'win32com', 'win32api', 'pythoncom', 'pywintypes', '_win32sysloader', 'win32com.gen_py', 'win32com.shell', 'pkg_resources.extern.appdirs', 'pkg_resources._vendor.packaging.__about__', 'pkg_resources.extern.packaging', 'pkg_resources.extern.packaging.version', 'pkg_resources.extern.packaging._structures', 'pkg_resources.extern.packaging.specifiers', 'pkg_resources.extern.packaging._compat', 'pkg_resources.extern.packaging.requirements', 'copy', 'pprint', 'pkg_resources.extern.pyparsing', 'pkg_resources.extern.six.moves.urllib', 'pkg_resources.extern.packaging.markers', 'pkg_resources.py2_warn', 'configparser', 'distutils', 'distutils.util', 'distutils.errors', 'distutils.dep_util', 'distutils.spawn', 'distutils.debug', 'distutils.log', 'periodictable', 'periodictable.core', 'periodictable.constants', 'periodictable.mass', 'periodictable.density', 'bumps', 'tinycc', 'sas.sascalc', 'sas.sascalc.calculator', 'sas.sasview', 'distutils.version', 'sas._config', 'sasmodels', 'sasmodels.custom', 'sas.sasview.sasview', 'multiprocessing', 'multiprocessing.context', 'multiprocessing.process', 'multiprocessing.reduction', '__mp_main__', 'matplotlib', 'six', 'matplotlib.cbook', 'six.moves', 'glob', 'gzip', 'numbers', 'numpy', 'numpy._globals', 'numpy.__config__', 'numpy.version', 'numpy._distributor_init', 'numpy.core', 'numpy.core.multiarray', 'numpy.core.overrides', 'numpy.core._multiarray_umath', 'numpy.compat', 'numpy.compat._inspect', 'numpy.compat.py3k', 'pathlib', 'numpy.core.umath', 'numpy.core.numerictypes', 'numpy.core._string_helpers', 'numpy.core._type_aliases', 'numpy.core._dtype', 'numpy.core.numeric', 'numpy.core.shape_base', 'numpy.core._asarray', 'numpy.core.fromnumeric', 'numpy.core._methods', 'numpy.core._exceptions', 'numpy.core._ufunc_config', 'numpy.core.arrayprint', 'numpy.core.defchararray', 'numpy.core.records', 'numpy.core.memmap', 'numpy.core.function_base', 'numpy.core.machar', 'numpy.core.getlimits', 'numpy.core.einsumfunc', 'numpy.core._add_newdocs', 'numpy.core._multiarray_tests', 'numpy.core._dtype_ctypes', '_ctypes', 'ctypes', 'ctypes._endian', 'numpy.core._internal', 'numpy._pytesttester', 'numpy.lib', 'numpy.lib.mixins', 'numpy.lib.scimath', 'numpy.lib.type_check', 'numpy.lib.ufunclike', 'numpy.lib.index_tricks', 'numpy.matrixlib', 'numpy.matrixlib.defmatrix', 'numpy.linalg', 'numpy.linalg.linalg', 'numpy.lib.twodim_base', 'numpy.linalg.lapack_lite', 'numpy.linalg._umath_linalg', 'numpy.lib.function_base', 'numpy.lib.histograms', 'numpy.lib.stride_tricks', 'numpy.lib.nanfunctions', 'numpy.lib.shape_base', 'numpy.lib.polynomial', 'numpy.lib.utils', 'numpy.lib.arraysetops', 'numpy.lib.npyio', 'numpy.lib.format', 'numpy.lib._datasource', 'numpy.lib._iotools', 'numpy.lib.financial', 'decimal', '_decimal', 'numpy.lib.arrayterator', 'numpy.lib.arraypad', 'numpy.lib._version', 'numpy.fft', 'numpy.fft._pocketfft', 'numpy.fft._pocketfft_internal', 'numpy.fft.helper', 'numpy.polynomial', 'numpy.polynomial.polynomial', 'numpy.polynomial.polyutils', 'numpy.polynomial._polybase', 'numpy.polynomial.chebyshev', 'numpy.polynomial.legendre', 'numpy.polynomial.hermite', 'numpy.polynomial.hermite_e', 'numpy.polynomial.laguerre', 'numpy.random', 'numpy.random._pickle', 'numpy.random.mtrand', 'cython_runtime', 'numpy.random._bit_generator', '_cython_0_29_14', 'numpy.random._common', 'secrets', 'hmac', 'numpy.random._bounded_integers', 'numpy.random._mt19937', 'numpy.random._philox', 'numpy.random._pcg64', 'numpy.random._sfc64', 'numpy.random._generator', 'numpy.ctypeslib', 'numpy.ma', 'numpy.ma.core', 'numpy.ma.extras', 'numpy.testing', 'unittest', 'unittest.result', 'unittest.util', 'unittest.case', 'difflib', 'unittest.suite', 'unittest.loader', 'unittest.main', 'argparse', 'gettext', 'unittest.runner', 'unittest.signals', 'numpy.testing._private', 'numpy.testing._private.utils', 'gc', 'numpy.testing._private.decorators', 'numpy.testing._private.nosetester', 'matplotlib.cbook.deprecation', 'matplotlib.cbook._backports', 'matplotlib.compat', 'matplotlib.compat.subprocess', 'matplotlib.rcsetup', 'matplotlib.testing', 'matplotlib.fontconfig_pattern', 'pyparsing', 'matplotlib.colors', 'matplotlib._color_data', 'cycler', 'six.moves.urllib', 'six.moves.urllib.request', 'urllib.request', 'http', 'http.client', 'email.message', 'uu', 'email._encoded_words', 'email.iterators', 'ssl', 'ipaddress', '_ssl', 'urllib.error', 'urllib.response', 'nturl2path', 'matplotlib._version', 'json', 'json.decoder', 'json.scanner', '_json', 'json.encoder', 'dateutil', 'dateutil._version']
11:14:18 - DEBUG : matplotlib: 409: CACHEDIR=C:\Users\smk78\.sasview\.matplotlib
11:14:18 - DEBUG : matplotlib.font_manager:1468: Using fontManager instance from C:\Users\smk78\.sasview\.matplotlib\fontList.json
11:14:18 - INFO : sas._config: 114: GuiManager loaded C:\Users\smk78\.sasview\config\custom_config.py
11:14:18 - INFO : sas.sasview.sasview: 223: You have not set the SASVIEW_WX_VERSION environment variable, so using default version of wxPython.
Traceback (most recent call last):
  File "run.py", line 186, in <module>
    run_gui()
  File "D:\SasViewCodeDev\ticket1583-numba\src\sas\sasview\sasview.py", line 284, in run_gui
    setup_wx()
  File "D:\SasViewCodeDev\ticket1583-numba\src\sas\sasview\sasview.py", line 225, in setup_wx
    import wx
ModuleNotFoundError: No module named 'wx'
```
As a sanity check, I changed to my ESS_GUI master folder and tried compiling and running that in the same development environment. Worked fine.
Any ideas?
Why is run.py complaining about wx in this Qt version?

**Comment by smk78** [comment]
Curiously, if I try building and running this branch under Anaconda2, it runs...

**Comment by pkienzle** [comment]
Are you sure that you are on the ticket_1583_pr_numba branch, and not the
master branch?

If you have gitbash available, then start the gitbash console and enter:

    cd /d/SasViewCodeDev/ticket1583-numba
    git status

BTW, I'm not seeing this conversation on github with the ticket... no idea
why.

- Paul

**Comment by smk78** [comment]
@pkienzle : yes, sorry, I was in the wrong branch. @rozyczko put me right on Slack so I then deleted my comment. Unfortunately I then had a meeting before I could finish cleaning up!

Anyway, looks good to merge.

**Pull request merged**
