### PR TITLE
Load in Mask Data column from NCNR 2D data.

### PR DESCRIPTION
**Pull request by krzywon**
The 2D data format from the VSANS instrument at the NCNR is now outputting a mask flag for each data point. This should read in the mask and format it so SasView can use it.

NB - I have no data sets with the mask column to test. The latest release of the Igor Macros (v7.93 - June 12, 2019) adds the mask data to the reduced data file. This PR may (should?) never get merged into master because we are actively working on writing VSANS data in NXcanSAS, which may supercede the .DAT format.

### CODE REVIEW

**Comment by butlerpd** [comment]
ready for testing on Win64

**Comment by krzywon** [comment]
Masks loaded in from example files appear jagged along the masking edge when a detector tube is masked anywhere along the tube. When a full tube is masked, the masking edge appears clean. The mask appears to be loading in as written to the file, so the issue is currently being looked into on the Igor side.

The image below shows masked fits for two panels of a single VSANS measurement. sans34736_ML.DAT has vertical detector tubes, and the left mask edge is evenly applied, but the top and bottom are not. sans34736_FB.DAT has horizontal detector tubes, with rectangular masks on both sides of the detector and a triangular mask in the upper left corner. No part of the mask is evenly applied.

JaggedMasking

**Comment by butlerpd** [comment]
ready for testing on Win64

**Comment by butlerpd** [comment]
ready for testing on Win64

**Comment by butlerpd** [comment]
ready for testing on Win64

**Comment by krzywon** [comment]
Looking through the console log of the pull request build, the build server is using the python p(r) invertor, rather than the C invertor still used by this PR. The 3 failing tests are the same 3 failing in master that are being addressed with #1387. @wpotrzebowski can you explain this behavior?

**Comment by pkienzle** [comment]
The failures should be resolved by #1402.  I kept the fix minimal so it can be quickly reviewed and merged.

**Comment by butlerpd** [comment]
ready for testing on Win64

**Comment by krzywon** [comment]
An error/warning is *supposed to* pop up when a fully masked data set is loaded, but that is tied to what is put into the console log. On the Windows build for this PR, nothing is being written to the console log. I'm not sure if this is a build server issue or a SasView issue, but will take some investigating.

**Pull request merged**
