### PR TITLE
Include SasData documentation in SasView

### PR DESCRIPTION
**Pull request by krzywon**
## Description

This PR integrates the documentation generated by the `sasdata` package into SasView using `build_sphinx.py` and CI.

This is reliant on the work in https://github.com/SasView/sasdata/pull/53 and uses the associated `sasdata` branch in `ci.yml`.

## How Has This Been Tested?

CI output

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by llimeht — APPROVED** [review]
Looks good. 

- I assume https://github.com/SasView/sasdata/pull/53 will get get merged first and then `ci.yml` will get updated prior to merging this
- Is it worth folding the `sphinx-apidoc` and `sphinx-build` calls that are duplicated here and in `sasdata/.github/workflows/test.yml` into the `doc/Makefile`? (in the same way as `bumps` and `sasmodels` have done so that it's a uniform interface to the three)
- `retrieve_sasdata_docs` is currently necessary but this sort of layout is not nice to new contributors with the complexity it brings to getting started with sasview, also not nice for downstream people who will have to come up with ways of circumventing it.

All this work reminds me of #2421 again btw.

**Comment by krzywon** [comment]
> * I assume [29: Building sasdata documentation sasdata#53](https://github.com/SasView/sasdata/pull/53) will get get merged first and then `ci.yml` will get updated prior to merging this

That's the expectation.

> * Is it worth folding the `sphinx-apidoc` and `sphinx-build` calls that are duplicated here and in `sasdata/.github/workflows/test.yml` into the `doc/Makefile`? (in the same way as `bumps` and `sasmodels` have done so that it's a uniform interface to the three)

Good catch. I missed that. I'll make those changes.

> All this work reminds me of #2421 again btw.

Agreed. At the last code camp, we started to look into combining everything into a single repository (sasmodels and sasdata included) and using CI to create separate releases for each 'external' repo. This would eliminate a lot of this hassle, including your first point, but continue to allow a cleaner separation of the different code sections. That is still a WIP.

**Comment by wpotrzebowski** [comment]
Tested on Mac. Works fine. In my opinion we should merge it

**Comment by wpotrzebowski** [comment]
@krzywon  any objections to merging it?

**Comment by krzywon** [comment]
@wpotrzebowski, SasView/sasdata#53 must be first merged and then I need to point the CI here to sasdata master.

**Comment by wpotrzebowski** [comment]
Tested on Mac. As discussed at the call I am merging it.

**Pull request merged**
