### PR TITLE
Try a new installer script with INNO6

### PR DESCRIPTION
**Pull request by rozyczko**
Test for a new installer script allowing users to choose admin/non-admin installation.

### CODE REVIEW

**Comment by rozyczko** [comment]
5.0 Ready for testing on Win

**Comment by rozyczko** [comment]
`new_installer.iss` is in repo and it is being used to create the package.
I have not updated the generator script because I don't think running the script makes any sense?
The paths inside are relative and the script can be modified if needed so.

**Comment by krzywon** [comment]
I'm talking about the original `installer.iss`, not the `new_installer.iss` you've added here. Doesn't `installer_generator64.py` create `installer.iss` when the batch script is run? Creating a second iss file seems redundant and makes the generator script obsolete.

**Comment by rozyczko** [comment]
Yes indeed. It will be removed.

**Comment by RichardHeenan** [comment]
Tested on Win10 Home, worked fine (no admin option there, so it just installed it, but to G:\ not program files as not enough space there), no issues with #1623 either.

**Comment by rozyczko** [comment]
The installer for this PR is available here:
https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/48/artifact/sasview/dist/setupSasView.exe

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on Win

**Comment by smk78** [comment]
I noted that Build https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/49/ that @wpotrzebowski launched had failed so instead I tested this:

> The installer for this PR is available here:
> https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/48/artifact/sasview/dist/setupSasView.exe

From a standard user account on a corporate W10/x64, having first uninstalled an already installed Mk2 5.0.3RC1 from the release page:

image
Selected Install for me only
image
On clicking Next it offered c:\SasView-5.0.3
image
Which I modified to c:\SasView-5.0.3RC1. On clicking Next
image
On clicking Next
image
On clicking Install
image
image
Installation completed and on clicking Finish, SasView started
image

**Comment by smk78** [comment]
Functionally this branch seems good to merge. Why did the PullRequest Builder fail?

**Comment by rozyczko** [comment]
Thanks for testing this PR, @smk78 . The branch was fixed and will now build. The new `installer.iss` file was being ignored by `.gitignore` and I failed to notice it not being pushed.

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by rozyczko** [comment]
5.0 ready for testing on Win

**Comment by smk78** [comment]
Just tested installation of Jenkins build 53 which should be the last one @wpotrzebowski initiated above. All good.

**Pull request merged**
