### PR TITLE
Slicer extension 1344

### PR DESCRIPTION
**Pull request by butlerpd**
This is a start at addressing #1344.  It only addresses the "folding" issue, and only for the boxslicer the code for which, as stated in the issue, was already present but was hard coded to `fold = True` in the GUI and `fold = False` in sascalc.

The GUI is particularly ugly at present in that the slicer parameter editor assumes all parameters are floats.  This works since any number other than 0 is true and 0 is false but ultimately allowing for a parameter by parameter editor would be the right answer making the fold boolean a checkbox.  This also is probably not possible for 5.0.4-rc1 in which case I would recommend that we merge this but keep the branch active. It still allows the functionality to be changed and should be a benign change?

### CODE REVIEW

**Comment by butlerpd** [comment]
ready for testing on Win

**Comment by butlerpd** [comment]
Note that the functionality may be a bit painful due to the outstanding Slicer Parameter Editor outlined in issues #1766.  The Editor is the only way to change the number of points or this flag.

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Review by wpotrzebowski — APPROVED** [review]

**Comment by wpotrzebowski** [comment]
Code looks good but I would agree that in the long term we need some kind of checkbox rather than number field. I've tested functionality but wasn't sure if I am doing right thing (as I have little experience with slicers functionality in general).

**Pull request merged**
