### PR TITLE
Create Release Notes option in Help Menu and popup box

### PR DESCRIPTION
**Pull request by smk78**
What does __revision__ do (in releasebox.py)? It was in acknowledgebox.py that I used as a template (that @krzywon wrote)...

### CODE REVIEW

**Comment by smk78** [comment]
Have revised the action of Help >> Release Notes as discussed on todays call. See #1176 for more info.
Ready for testing.

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Win64

**Comment by wpotrzebowski** [comment]
Tested on OSX and Win7 and looks good.

**Comment by smk78** [comment]
@ajj says merge!

**Comment by smk78** [comment]
Closes #1176

**Pull request merged**
