### PR TITLE
Add v6 tutorials

### PR DESCRIPTION
**Pull request by smk78**
## Description

Adds the v6 tutorials to the release branch.

NB: the corresponding v5 tutorials in the folder should be removed.

### CODE REVIEW

**Comment by lucas-wilkins** [comment]
@smk78 I don't think this PR does what you want it to. Says merge `release_6.0.0` into `main`.

**Review by lucas-wilkins — CHANGES_REQUESTED** [review]
See other comment!!!!

**Comment by krzywon** [comment]
The tutorials are already in the release_6.0.0 branch. @smk78 pushed them directly into it. This PR can likely be closed.

**Comment by krzywon** [comment]
> But don't they also need to go into main?

They will be. Once v6 is finalized, we will merge the entire release branch back into main. Until then, we can wait on this.

**Pull request closed without merging**
