### PR TITLE
Enable Param Paste and test the content on action. #1536

### PR DESCRIPTION
**Pull request by rozyczko**

### CODE REVIEW

**Comment by pkienzle** [comment]
Does this PR depend on another?

I tried testing paste on Mac and received the following error in the console:
```
11:57:29 - ERROR: Traceback (most recent call last):
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py", line 113, in onParamPaste
    self.currentTab.onParameterPaste()
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 4005, in onParameterPaste
    self.updatePageWithParameters(line_dict)
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 4092, in updatePageWithParameters
    button_id = int(line_dict['weighting'][0])
KeyError: 'weighting'
```

**Comment by rozyczko** [comment]
Fixed the missing key check.

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on OSX

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on Win

**Pull request merged**
