### PR TITLE
Log explorer fix

### PR DESCRIPTION
**Pull request by smalex-z**
## Description

Fix found by @pkienzle. Fixes issue stemming from move to Pyside6 from pyqt5, where the Log Explorer stopped working after the switch. Previously, there were two instances of the function `emit()` that were inherited into the handler- one from logging.handler, and one from QObject.

Fixes #2538 

## How Has This Been Tested?

Run Sasview. Log messages should now show up in the Log Explorer.

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by rozyczko — COMMENTED** [review]
Works fine but we now see DEBUG level logs, which were not printed by default before.

**Comment by krzywon** [comment]
Note for clarity: the debug level logs are shown in **production**, not just from run.py. I'm leaning toward approving this PR and documenting the debug issues in a separate ticket unless someone smarter than me can find a simple solution.

**Comment by pkienzle** [comment]
The default logger level is set to DEBUG in `sasview/src/sas/system/log.ini`:
https://github.com/SasView/sasview/blob/9f5eab2605d42e0c1a2ea285293a34eaf4103e2b/src/sas/system/log.ini#L46-L49
I suspect you will need a new handler entry to set the level to WARNING:
```ini
[handlers]
keys=console,log_file,qtconsole

…

[handler_qtconsole]
class=sas.qtgui.Utilities.SasviewLogger
formatter=simple
level=WARNING
args=tuple()
```

I don't know which takes precedence, (a) the simple formatter specified in the ini file:
https://github.com/SasView/sasview/blob/9f5eab2605d42e0c1a2ea285293a34eaf4103e2b/src/sas/system/log.ini#L11-L16
or (b) the formatter specified in the code:
https://github.com/SasView/sasview/blob/86c0879b4ab5d20bec74d1c2c2039ebf57f727b6/src/sas/qtgui/Utilities/SasviewLogger.py#L31-L34

I would expect (a) in the code to set the default and (b) in the config file to override. The latter contains an additional format item `%(name)s` so you should be able to tell which one is in use.

The docs for `sas.system.log.SetupLogger._find_config_file` claims that it will look for the .ini file in `~/.sasview` while in debug mode, but from the code that appears to not be the case:
https://github.com/SasView/sasview/blob/9f5eab2605d42e0c1a2ea285293a34eaf4103e2b/src/sas/system/log.py#L60-L75

It might be handy to allow the user to turn on DEBUG when they have problems and we want them to turn it on for more details (either on the command line, or in a `~/.sasview/log.ini` override file).

**Comment by smalex-z** [comment]
I'm just getting a module object is not callable error. Would recommend merging unless someone else can fix it.

**Pull request merged**
