### PR TITLE
Sasdata 8: Move example data to sasdata package

### PR DESCRIPTION
**Pull request by krzywon**
## Description

Example data are removed from the sasview/sasview repo, and, instead, are copied from the sasdata build. This is the SasView corollary to sasview/sasdata#49 which is now merged.

## How Has This Been Tested?

CI completes successfully

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by krzywon** [comment]
Question from @lucas-wilkins: will the new sasdata import work when the data is integrated with sasview?

**Comment by llimeht** [comment]
Moving the files at CI time reminds me of #2421. Requiring multiple projects be checked out in a particular directory structure and then moving files between them at test and build time is an interesting symptom.

**Comment by smk78** [comment]
Can I suggest you merge https://github.com/SasView/sasdata/pull/58 **first** so you get the latest copy of the example data and updated testdata_help.

**Comment by butlerpd** [comment]
I'm not sure I follow @smk78 comment? Presumably this PR removes the data files that are now already in sasdata main? This would be independent of any new data files being added to sasdata would it not? or am I misunderstanding the PR?

**Review by butlerpd — APPROVED** [review]
It was agreed at Tuesday's call that it was ready to merge but apparently nobody clicked the approve button. Doing so now

**Pull request merged**
