### PR TITLE
WIP. DONT MERGE. Allow polydisperse parameters to be constrained

### PR DESCRIPTION
**Pull request by rozyczko**
This is a fix to Richard's issue from https://github.com/SasView/sasview/issues/1376

### CODE REVIEW

**Comment by RichardHeenan** [comment]
Built this 5.0 branch locally, previous project saved above did not work when loaded, so pulled in my core, shell, drop data sets to start from scratch. Added some constraints, why are they showing as M3:scale=M2.scale ? (i.e. a mix of use of : and . ), then added one on M3.radius_width = M1.radius_width, this failed to operate properly and the constraint disappeared when I added another one, meanwhile getting error messages as below.

Likely several things going on, if my build is OK ????  


17:10:06 - ERROR: SasView threw exception: must be str, not NoneType
Traceback (most recent call last):
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\ConstraintWidget.py", line 821, in initializeFitList
    self.updateFitLine(tab)
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\ConstraintWidget.py", line 768, in updateFitLine
    label = moniker + ":"+ constraint_name[0] + " = " + constraint_name[1]
TypeError: must be str, not NoneType
17:10:18 - ERROR: SasView threw exception: must be str, not NoneType
Traceback (most recent call last):
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\ConstraintWidget.py", line 821, in initializeFitList
    self.updateFitLine(tab)
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\ConstraintWidget.py", line 768, in updateFitLine
    label = moniker + ":"+ constraint_name[0] + " = " + constraint_name[1]
TypeError: must be str, not NoneType

**Comment by RichardHeenan** [comment]
Started afresh, trying to add even simple constraints is not working for me in this branch, and getting more of the error messages.

**Comment by wpotrzebowski** [comment]
5.0 ready for testing on Win

**Comment by wpotrzebowski** [comment]
@RichardHeenan: there is an intsaller at https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/20/

**Comment by RichardHeenan** [comment]
Installed the windows version for this branch. Not getting very far with testing constraints yet, as just doing a simple fit on one data set, as soon as I try to fit a polydispersity, the fit to radius and radius_pd go completely mad (e.g. radius drops from 30 to 0.3 Ang and pd goes very large, fit gets much worse).  The fit results for _pd are also ignoring the max & min values.  e.g. try fitting the microemulsion drop or shell contrast to polydisp sphere or core-shell sphere respectively.

**Comment by RichardHeenan** [comment]
Something is broken in "polydispersity", this likely needs a new ticket.
I compared  my local build of sasview ESS_GUI + sasmodels master with release 4.2
Report1 below uses the best fit parameter from 4.2 release, fitting scale, radius & radius_width, with just a compute in my local build, this looks good, BUT hitting fit gives results in report2, which are plain crazy,  radius drops from 22 to 0.2 ang, radius_width goes to zero, which is outside the min value set at  0.02. Would some other people please test likewise.

[fit_report1_5Sept2019.pdf](https://github.com/SasView/sasview/files/3579178/fit_report1_5Sept2019.pdf)
[fit_report2_5Sept2019.pdf](https://github.com/SasView/sasview/files/3579181/fit_report2_5Sept2019.pdf)

**Comment by lucas-wilkins** [comment]
What's the status of this, is it being actively worked on?

**Comment by butlerpd** [comment]
This needs a bit (a lot?) more love so closing the PR but keeping the branch for more work

**Comment by lucas-wilkins** [comment]
Reopening, as I'm working on it, and this pages doesn't seem to update without being open

**Comment by lucas-wilkins** [comment]
What exactly is remaining here? Happy to chat about it @rozyczko (though I'll be away after today for 3 weeks)

**Comment by lucas-wilkins** [comment]
Going to close this again for now - its just hanging around.

**Comment by rozyczko** [comment]
good. I think it was originally created to enable creation of artifacts on Jenkins, where we had them only on PR commits

**Comment by butlerpd** [comment]
When you say 3 weeks @lucas-wilkins, I assume that the 2nd week is because you'll be at code camp ... with @rozyczko and the rest of us?  Maybe you can sort out what needs doing then?

**Comment by lucas-wilkins** [comment]
> When you say 3 weeks @lucas-wilkins, I assume that the 2nd week is because you'll be at code camp ... with @rozyczko and the rest of us? Maybe you can sort out what needs doing then?

When I said 3 weeks it was 4 months ago!

**Pull request closed without merging**
