### PR TITLE
initial version of modified Send To button

### PR DESCRIPTION
**Pull request by rozyczko**
## Description

Let's have people look at this redesign and express their opinions on functionality/look.

This PR is for a small change in what the "Send to" button looks like and behaves. QPushButton has been replaced with QToolButton, with drop down menu. 
The original functionality is retained - just clicking the button will send the selected dataset(s) to new tab(s) in fitting.
Clicking on the arrow in the right bottom corner of the Send To button will open a small menu allowing users to replace the data with the current dataset instead. This mimicks the "swap" button and slightly declutters the area.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
It is functional but the button on Mac still doesn't look very nice

**Comment by wpotrzebowski** [comment]
Looks better but can probably be improved
Screenshot 2023-09-21 at 18 26 53

**Comment by wpotrzebowski** [comment]
Now the error is:
```
17:19:12 - ERROR: Traceback (most recent call last):
  File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 3208, in complete1D
  File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 3332, in calculateResiduals
  File "sas/qtgui/Perspectives/Fitting/FittingUtilities.py", line 438, in calculateChi2
ValueError: operands could not be broadcast together with shapes (192,) (0,)
```

**Review by wpotrzebowski — APPROVED** [review]

**Comment by rozyczko** [comment]
Since @wpotrzebowski's observation is not directly related to this PR, can it be merged?

**Pull request merged**
