### PR TITLE
2885 logos do not appear in about box

### LINKED ISSUE #2885: logos do not appear in about box
**Describe the bug**
The Logos appear as blank boxes in the About box. The underlying links still work and open up the relevant page in the browser 

**SasView version (please complete the following information):**
 - Version: 6.0.0a1

**Operating system (please complete the following information):**
 - OS: e.g. Windows 10

**Additional context**
This needs to be fixed as part of the 6.0 release process

### PR DESCRIPTION
**Pull request by lucas-wilkins**
Fixes #2885 - icons not appearing

* Also updated the icons for the insitutions, many now SVGs. 
* Reworked the box a little
* Minor change to some menu text

### CODE REVIEW

**Comment by lucas-wilkins** [comment]
Link this issue github! Closes #2885

**Review by krzywon — APPROVED** [review]
I tested the installer on Windows. The images are bundled properly and show up in the about box. The window is also cleaner to look at.

One suggestion - the new buttons give no hover feedback they are links. I only knew they were because of the code.

**Comment by lucas-wilkins** [comment]
> One suggestion - the new buttons give no hover feedback they are links. I only knew they were because of the code.

I can fix that, probably

**Comment by lucas-wilkins** [comment]
@krzywon There were some limitations on what kind of feedback works, as image handling in Qt is pretty unpredictable and the logos are all different sizes and formats. Hope just removing the border is enough.

**Comment by wpotrzebowski** [comment]
It looks nice (much nicer than the previous one). Maybe 6.0.0b1 font can be slightly bigger. 

The question is if we should add more logos to match updated contributors  list?  This will make this box probably too big and I am thinking if it is not better to skip the logos and just refer yo people list on website. 
Screenshot 2024-06-25 at 06 05 54

**Comment by butlerpd** [comment]
check and see if we are missing any logos that really need to be added.

**Pull request merged**
