### PR TITLE
ticket 993

### PR DESCRIPTION
**Pull request by rozyczko**
Added explicit 64 bit installer directives to the INNO script generator

### CODE REVIEW

**Comment by rozyczko** [comment]
Ready for testing on Win64

**Comment by rozyczko** [comment]
Ready for testing on Win32

**Comment by krzywon** [comment]
Both the Win32 and Win64 installers now default to the x64 Program Files directory. We are going away from the 32 bit build, so long term this isn't an issue, but could lead to confusion for the remainder of the 4.x releases.

**Comment by rozyczko** [comment]
Ready for testing on Win32

**Comment by rozyczko** [comment]
Ready for testing on Win64

**Comment by butlerpd** [comment]
LOL ... I thought we'd agreed we were not going to worry about a conditional for now? BTW does anybody even have a 32 bit machine to test that it does the right thing in that case?  Also moot I suppose if we are not going to deliver a 32 bit version of 4.2.

**Comment by rozyczko** [comment]
We did agree but the change was trivial and considering we don't know whether we're releasing only 64bit on Windows or keep the 32bit installer for one more release, I decided to make it behave correctly.

**Comment by butlerpd** [comment]
Now checked also on an old windows XP (32 bit) machine and it seems to work. At least it installs, loads properly and the documentation also loads. Did no real functionality testing. If we DO release a 32 bit we should test a bit more.

**Pull request merged**
