### PR TITLE
Documentation updates (ESS_GUI)

### PR DESCRIPTION
**Pull request by smk78**
Merge doc updates from the ESS_GUI (QtSasView) documentation branch

### CODE REVIEW

**Comment by krzywon** [comment]
I don't think you want to merge this into master, but ESS_GUI and this branch are level, so github won't let me change the base. @smk78 what are you trying to accomplish here?

**Comment by smk78** [comment]
I was trying to set up a PR to merge changes from ESS_documentation into ESS_GUI. Thanks for spotting my error @krzywon ! What's my best plan here: if I just delete (without merging) this PR is that ok?

**Comment by butlerpd** [comment]
Humm I just tried to change the branch it is merging to and looks like it is messing up worse --- think indeed lets delete the pull request and start over.  Maybe I screwed up when creating the branch?

**Comment by butlerpd** [comment]
closing this PR given issues.  Will be easier to start over and see what the problem is for future reference.

**Pull request merged**
