### PR TITLE
Corfunc Docs

### PR DESCRIPTION
**Pull request by lucas-wilkins**
New corfunc docs, see #2674 for details.

### CODE REVIEW

**Comment by smk78** [comment]
This is a nice set of documentation. I can see the Theory one becoming a quasi-primary reference once it's discoverable!

A few things I spotted:

In **corfunc-theory**:
_In Overview:_
Typo: In "such that there is no spatial correlations between particles" replace "is" by "are"
_In Formal Description:_
"_t_" and "_s_" are undefined
_In the Gamma1 projection:_
Typo: "This the case" should presumably be "This is the case"?
_In the Gamma3 projection:_
Typo: "stradians" should be "steradians"
In the second equation phi is undefined
The equation under the line "Where phi is a solid angle element" needs reformatting as it incorporates some text 

In **corfunc-technical**:
_In Transformation:_
Could give the equation for Q*, I guess?
_In Interpretation:_
Can we give the definition of the Stribeck polydispersity

In **corfunc-how-to**:
_In Options:_
Typo: In "where there is small errors in the transformed data" replace "is" by "are"
Typo: In "such as hard block is calculated" replace "is" by "are"
_In Output:_
Please could we add a note warning that if the transformed data CSV file is read back into SasView it will be interpreted as (Q,I(Q),dI,dQ)!!!

**Review by smk78 — CHANGES_REQUESTED** [review]
Looking good! Just a few documentation issues and (unfortunately) a bug saving plots.
See Conversation for details.

**Comment by lucas-wilkins** [comment]
> This is a nice set of documentation. I can see the Theory one becoming a quasi-primary reference once it's discoverable!
> 
> A few things I spotted:
> 
> In **corfunc-theory**: _In Overview:_ Typo: In "such that there is no spatial correlations between particles" replace "is" by "are" _In Formal Description:_ "_t_" and "_s_" are undefined _In the Gamma1 projection:_ Typo: "This the case" should presumably be "This is the case"? _In the Gamma3 projection:_ Typo: "stradians" should be "steradians" In the second equation phi is undefined The equation under the line "Where phi is a solid angle element" needs reformatting as it incorporates some text

All done

> In **corfunc-technical**: _In Transformation:_ Could give the equation for Q*, I guess? _In Interpretation:_ Can we give the definition of the Stribeck polydispersity

Opened new issue for these - #2835 

> In **corfunc-how-to**: _In Options:_ Typo: In "where there is small errors in the transformed data" replace "is" by "are" Typo: In "such as hard block is calculated" replace "is" by "are" _In Output:_ Please could we add a note warning that if the transformed data CSV file is read back into SasView it will be interpreted as (Q,I(Q),dI,dQ)!!!

Done

**Review by smk78 — APPROVED** [review]
This PR is now suitable to merge. But note https://github.com/SasView/sasview/issues/2835

**Pull request merged**
