### PR TITLE
Keyerror fix 1996

### PR DESCRIPTION
**Pull request by rozyczko**
Sometimes the main category dict does not contain custom structure
factors so a check needs to be added.

### CODE REVIEW

**Review by smk78 — DISMISSED** [review]
Built branch on W10/x64 and repeated example shown in https://github.com/SasView/sasview/issues/1996.

This fix rectifies the issue reported.

**Comment by butlerpd** [comment]
@rozyczko is there a reason that mac notarization is failing for this PR but not for PR #1994?  Otherwise it looks like we could merge this right?

**Comment by rozyczko** [comment]
Err not really? Maybe a random build host hiccup?

**Comment by butlerpd** [comment]
So trying to merge release 5.0.5 into this branch (to force a github action) I discovered that this branch was erroneously created from main rather than the release_5.0.5 branch on Dec 15, 2021.  I do only see 3 commits to master between Nov 13 (date the release branch was created) and Dec 15 that that are not in the release branch and I don't think any of them matter (changes to action yml and issue templates) so it should be fine to merge 5.0.5 into this (with all 131 commits that come with that 😃, but thought I'd ask before blindly moving forward.

**Comment by wpotrzebowski** [comment]
> So trying to merge release 5.0.5 into this branch (to force a github action) I discovered that this branch was erroneously created from main rather than the release_5.0.5 branch on Dec 15, 2021. I do only see 3 commits to master between Nov 13 (date the release branch was created) and Dec 15 that that are not in the release branch and I don't think any of them matter (changes to action yml and issue templates) so it should be fine to merge 5.0.5 into this (with all 131 commits that come with that 😃, but thought I'd ask before blindly moving forward.

I think it should be fine. It may also be easier to add one line fix to installer.yml. Let me do it!

**Comment by butlerpd** [comment]
@smk78 I think meant to approve this? Or do we need another review?

**Review by butlerpd — APPROVED** [review]
Looking at code change and given @smk78 review I am approving this PR

**Pull request merged**
