### PR TITLE
Update reader and writer for NXcanSAS v1.1 changes (4.x)

### PR DESCRIPTION
**Pull request by krzywon**
As outlined in https://github.com/nexusformat/definitions/issues/765, the NXcanSAS definition is changing and the version number is being incremented. This PR should capture those changes.

This PR is specific to 4.x. PR #1531 is the same content for 5.x.

refs #1527

### CODE REVIEW

**Comment by smk78** [comment]
Pulled the branch, built and ran locally on W10/x64. Read & displayed existing v1.0 NXcanSAS .h5 files ok. Wrote out, read back in & displayed .h5 files from the graph windows (would these have been tagged v1.1?). Used the File Converter to convert a dataset to .h5 (would this also have been tagged v1.1?), read that back in and displayed it. So nothing in this PR breaks existing functionality with NXcanSAS. Was obviously unable to test loading of an externally produced v1.1 file as no one is yet producing them!

**Comment by smk78** [comment]
Files written from this branch build also read back in to release version.

**Comment by krzywon** [comment]
@smk78 Any new NXcanSAS files generated from this PR and the parallel one for 5.x should be tagged as v1.1.

nxcansas_writer.py line 116 `sasentry.attrs['version'] = '1.1'`

**Comment by smk78** [comment]
@krzywon: I can't figure out how to verify the version attribute in HDFView, but I _can_ see that the _radiation_ attribute is now _probe_.

I think this and the linked PR are good to merge.

**Comment by krzywon** [comment]
@smk78: The version number is an attribute linked to the SASentry. In HDFView, right click on the entry and select 'Show Attributes.'

**Comment by smk78** [comment]
@krzywon: Ok, I see it now! Thanks. Yes, I can see files written from this branch build tagged as 1.1.

**Pull request merged**
