### PR TITLE
[Release 5.0.6] 1911: Create config file if not found

### PR DESCRIPTION
**Pull request by krzywon**
## Description

This is an alternate fix for #1911 that should be used in all v5 releases. This fix won't be compatible with the main branch but is needed for v5.0.6.

## How Has This Been Tested?

Delete custom_config.py from your user directory and run this branch using run.py.

## Review Checklist (please remove items if they don't apply):

- [x] Code has been reviewed
- [x] Functionality has been tested
- [x] Windows installer (GH artifact) has been tested (installed and worked) 
- [x] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] Developers documentation is available and complete (if required)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by krzywon** [comment]
Please note, the failing tests are fixed by #2178 which is in the main branch, but not in the release branch yet.

**Review by butlerpd — APPROVED** [review]
Have now tested the commit installer and it works as advertised. 5.0.5 fails if I remove custom_config, but this version runs fine and just creates a new custom_config.py in the user folder.  So good to go I think

**Comment by butlerpd** [comment]
why are so many unit tests failing for this PR?

**Comment by llimeht** [comment]
Lots of tests failing because the patches for numpy 1.2x compatibility are needed.
https://github.com/SasView/sasview/commit/b1ab08c2a4e8fdade7f3e4cfecf3dfec38b8f3c5

**Comment by wpotrzebowski** [comment]
The installer seems to work fine. I haven't tried on the completely fresh system but was quite nasty to my setup to stress test it.

**Review by lucas-wilkins — APPROVED** [review]
Lol, OK.

**Comment by wpotrzebowski** [comment]
It seems that we should be ready to merge this one?

**Comment by butlerpd** [comment]
It seem so to me. @krzywon, is there any reason we should not merge this? It seems to have been reviewed appropriately and approved?

**Pull request merged**
