### PR TITLE
New version of splash screen and icon

### PR DESCRIPTION
**Pull request by wpotrzebowski**
## Description

A new version of the splash screen as discussed in https://github.com/SasView/sasview/issues/2878.  I will also try to update icon in the same PR

Fixes # (issue/issues)

## How Has This Been Tested?

Start sasview and how the splash screen and icon looks like 

## Review Checklist:

[if using the editor, use `[x]` in place of `[ ]` to check a box]

**Documentation** (check at least one)
- [x] There is **nothing** that needs documenting
- [ ] Documentation changes are **in this PR**
- [ ] There is an **issue** open for the documentation (link?)

**Installers**
- [x] There is a chance this will affect the **installers**, if so
  - [ ] **Windows** installer (GH artifact) has been tested (installed and worked) 
  - [ ] **MacOSX** installer (GH artifact) has been tested (installed and worked) 

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by lucas-wilkins** [comment]
closes #2907

**Comment by wpotrzebowski** [comment]
I can see the splash screen when I run locally but not from the installer... This happens on Mac. Can someone else check if this is a reproducible behavior?

**Comment by smk78** [comment]
After download on Windows:
image

**Comment by smk78** [comment]
On launch on Windows:
image

**Comment by smk78** [comment]
But I still have the old ball icon in the toolbar:
image

**Comment by smk78** [comment]
Welcome:
image

**Comment by smk78** [comment]
Interestingly, the icons in the installation folder are also the old ones:
image

**Comment by smk78** [comment]
From what I'm reading there is no way to change the icon on an executable once it's installed (only the icon on a shortcut to an executable). So the old icon must be being associated with the sasview application somewhere in the installer build...

**Comment by lucas-wilkins** [comment]
I think the icon is specified in the .spec file, so it needs updating there, it might link to a different copy of the images (we have too many copies of the same images still)

**Comment by lucas-wilkins** [comment]
@wpotrzebowski Should be fixed!

**Comment by wpotrzebowski** [comment]
@lucas-wilkins Thanks for looking at it.
The installer seems to be crashing with 
`[96363] Failed to execute script 'sasview' due to unhandled exception: No module named 'sas.qtgui.images'
[96363] Traceback:
Traceback (most recent call last):
  File "sasview.py", line 15, in <module>
  File "sas/cli.py", line 161, in main
  File "sas/qtgui/MainWindow/MainWindow.py", line 92, in run_sasview
  File "sas/qtgui/MainWindow/MainWindow.py", line 63, in SplashScreen
  File "importlib/resources/_legacy.py", line 25, in wrapper
  File "importlib/resources/_legacy.py", line 46, in open_binary
  File "importlib/resources/_common.py", line 22, in files
  File "importlib/resources/_common.py", line 53, in get_package
  File "importlib/resources/_common.py", line 44, in resolve
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sas.qtgui.images'`

**Comment by lucas-wilkins** [comment]
@wpotrzebowski it might be because the installer has given it a different name (e.g. just images). I could change the path to images, but then the local dev will break. I'll see if I can add both paths "images" and "sas.qtgui.images" to the installer and have them point to the same place.

**Comment by wpotrzebowski** [comment]
Thanks @lucas-wilkins. It works now

**Comment by wpotrzebowski** [comment]
> Interestingly, the icons in the installation folder are also the old ones: image
> 
> But if I right click on the sasview app and do Properties it shows the new one! image

I've checked that spec file refers to updated icon files.

**Comment by wpotrzebowski** [comment]
I've replaced all possible icon files. Indeed, there are plenty. @smk78 can you please check if you still can see old ball in the installation folder?

**Comment by smk78** [comment]
@wpotrzebowski  I tried https://github.com/SasView/sasview/actions/runs/9789639783 on W10/x86.

The new logo appears on the installer file, and on the installation dialog box, _but not_ :
- on the shortcut that is created (if you check that option in the installation dialog)
- in the taskbar when the application starts!
- or on the sasview & unins00 applications in the installation folder

**Comment by lucas-wilkins** [comment]
Looks good

image

**Review by lucas-wilkins — APPROVED** [review]

**Pull request merged**
