### PR TITLE
v6.0.0: Final release notes

### PR DESCRIPTION
**Pull request by krzywon**
## Description

A final update to the release notes in preparation on the v6.0.0 release.

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by lucas-wilkins** [comment]
As the config changes we actively cherry picked away in 5.0.6 it didn't get a mention. As it fixes the main bug that people report, I thought it deserved a mention. I've added it to the features.

**Comment by smk78** [comment]
So I've made a couple more small changes, but overall I think these Release Notes are good to go.

However, I'm rather confused by the entry
```
One new model has been added to SasView since v5.0.6 was released:

[spin_structure_ferromagnets_3D](https://marketplace.sasview.org/models/140/) SANS in bulk ferromagnets by @stellhorn in https://github.com/SasView/sasmodels/pull/592
```

I've added the Marketplace link, but I don't see this model in RC2. Was RC2 built with sasmodels 1.0.8?

Is the _spin_structure_ferromagnets_3D_ model supposed to be a new 'library' model in 6.0.0 or does the text 'One new model has been added to SasView since v5.0.6 was released:' need to be removed?

**Review by smk78 — APPROVED** [review]
Approved subject to resolution of the comment above.

**Comment by krzywon** [comment]
> So I've made a couple more small changes, but overall I think these Release Notes are good to go.
> 
> However, I'm rather confused by the entry
> 
> ```
> One new model has been added to SasView since v5.0.6 was released:
> 
> [spin_structure_ferromagnets_3D](https://marketplace.sasview.org/models/140/) SANS in bulk ferromagnets by @stellhorn in https://github.com/SasView/sasmodels/pull/592
> ```
> 
> I've added the Marketplace link, but I don't see this model in RC2. Was RC2 built with sasmodels 1.0.8?
> 
> Is the _spin_structure_ferromagnets_3D_ model supposed to be a new 'library' model in 6.0.0 or does the text 'One new model has been added to SasView since v5.0.6 was released:' need to be removed?

I'll update this - it's called `micromagnetic_FF_3D` in sasmodels, not `spin_structure_ferromagnets_3D`.

**Pull request merged**
