### PR TITLE
4.2.0 fixes

### PR DESCRIPTION
**Pull request by lewisodriscoll**
This pull request contains smaller fixes for various tickets:
- Fixes [#967](http://trac.sasview.org/ticket/967) - Fitting uncertainties not shown
- Fixes [#906](http://trac.sasview.org/ticket/906) - Polydispersity values not shown in batch fit results
- Fixes [#986](http://trac.sasview.org/ticket/986) - Send to Fitting overwrites theory page

It also fixes a unit test for the corfunc perspective that was failing

The two reverted commits are now part of pull request #100

### CODE REVIEW

**Comment by trnielsen** [comment]
ready for testing on OSX

**Comment by trnielsen** [comment]
ready for testing on Win32

**Comment by trnielsen** [comment]
ready for testing on Linux

**Comment by butlerpd** [comment]
I don't see why one would need nsig or Npts as available columns for the spreadsheet.   At any rate if somebody decides they are needed they would be another ticket.  Since this answers the ticket we should merge it before it gets too far behind master.

**Pull request merged**
