### PR TITLE
Debuging report generation

### PR DESCRIPTION
**Pull request by wpotrzebowski**
This is not a true pull request but the only way to debug this problem as it can go through exactly the same building process as master

Please don't review at the moment!

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by pkienzle** [comment]
Looks like you specify the encoding directly in the CreatePDF call:

    https://stackoverflow.com/questions/12185464/python-pisa-utf8-issue

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Pull request closed without merging**
