### PR TITLE
2316: GPU and Optimizer Options in Preferences Window

### PR DESCRIPTION
**Pull request by krzywon**
## Description

The GPU and Optimizer selection tools now appear within the preferences panel rather than their own windows. This is a parallel PR to #2381. When both are merged, #2316 can be closed.

## How Has This Been Tested?

Run SasView, open the preferences window. GPU Options and Fitting Optimizers options are now included in the window.

If 'Cancel' is clicked, ensure all settings return to their original values
If 'Ok' or 'Apply' is clicked, ensure changes are applied.
If 'Test' is clicked on GPU Options panel, ensure tests run for selected GPU options.
If either menu option is selected, ensure the preferences panel opens to the desired option.

## Review Checklist (please remove items if they don't apply):

- [x] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)

### CODE REVIEW

**Comment by butlerpd** [comment]
Maybe we should ask @pbeaucage and @lucas-wilkins to take a look at? though both are out till January ...

**Review by lucas-wilkins — APPROVED** [review]

**Comment by lucas-wilkins** [comment]
Git-hub lost a bunch of my comments. The only one that might have mattered at all, was somewhere you could have used a set not a list for tracking the restart required fields.

**Comment by butlerpd** [comment]
why are tests failing?

**Comment by llimeht** [comment]
> why are tests failing?

It was failing to download some dependencies. I heard on the grapevine that the ubuntu archives had some issues in the last few days which would tally with that. I just hit retry on the failing actions and they have all succeeded.

**Comment by krzywon** [comment]
@lucas-wilkins, I changed the list to a set as you suggested. Can you give this one last quick look?

**Comment by lucas-wilkins** [comment]
> @lucas-wilkins, I changed the list to a set as you suggested. Can you give this one last quick look?

That's what I had in mind, yes.

**Pull request merged**
