### PR TITLE
Revert "Quote file names in ConvertUI"

### PR DESCRIPTION
**Pull request by wpotrzebowski**
It seems that Mac Installer is failing because of this merge. Testing if this actually the case

### CODE REVIEW

**Comment by krzywon** [comment]
I added a comma in line 37 so the line is now `run_line = ["pyside6-uic", in_file2 ", -o", out_file2]`. I have no preference either way.

**Comment by butlerpd** [comment]
@wpotrzebowski is reverting to the original that was changed (twice) based on @llimeht suggestion and concurence of @lucas-wilkins. It should of course have had a comma so that was broken.

Of course if using the subprocess is causing the problem for mac then maybe we have to go back to that. But I suspect the issue was the missing comma which is required in the subproccess call. In which case I would think we should stick with @krzywon fix instead.

**Comment by butlerpd** [comment]
As demonstrated by @caitwolf we also need to add `import subprocess` at the top. Duh!! Clearly I merged too fast and didn't even check the build. Very very bad form on my part. Apologies.

**Comment by wpotrzebowski** [comment]
Closing this PR as #2821 resolved the underlying problem

**Pull request closed without merging**
