### PR TITLE
move new pinned dependencies to pinned section.

### PR DESCRIPTION
**Pull request by butlerpd**
Just moves the 2 new pinned versions (numpy and scipy) to the pinned version of `requirements.txt` and adds comments as to why they are pinned.

### CODE REVIEW

**Comment by lucas-wilkins** [comment]
Fine, but why make two lists?

**Comment by butlerpd** [comment]
> Fine, but why make two lists?

two lists? Not sure I follow. @krzywon alphabetized and organized pinned vs unpinned (and OS specific) into sections a while back, I assume because we have so many dependencies we were doubling up and also losing track of what is pinned etc?  We then pinned numpy and scipy (which were not pinned) without moving them to the pinned section.  If this is not useful then we should remove that section and reorder all the pinned back into the list? What about OS specific in that case? Or should that PR never have been merged in the first place?

Or is there something I did that I'm not noticing? Sorry for my confusion.

**Comment by lucas-wilkins** [comment]
It doesn't really matter, just wondering why. It means you have to search in two parts of the file for a given package, not just one.

**Comment by rozyczko** [comment]
I think the current solution is cleaner since we don't have a particularly long list of dependencies. They all neatly fit even on a small screen and placing them in sections for standard, platform-dependent and pinned makes sense.
Maybe the pinned version section could go to the top, though, since it is the most important (?)

**Review by rozyczko — APPROVED** [review]

**Pull request merged**
