### PR TITLE
RC1: Fix for the release

### PR DESCRIPTION
**Pull request by krzywon**
## Description

This sets the config version back to 6.0.0. This should fix the issue with the release candidate.

## Review Checklist:

**Installers**
- [x] There is a chance this will affect the **installers**, if so
  - [x] **Windows** installer (GH artifact) has been tested (installed and worked) 
  - [x] **MacOSX** installer (GH artifact) has been tested (installed and worked) 

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by smk78 — APPROVED** [review]
Functionality test of artefact https://github.com/SasView/sasview/actions/runs/11167505645/job/31080657249?pr=3117 on W10/x64.
Installed, ran, and re-ran fine. The bug seems fixed.

**Comment by lucas-wilkins** [comment]
Windows one seems good. Trying to find the mac artefact.

**Comment by lucas-wilkins** [comment]
@krzywon The mac artefact seems to be missing.

**Comment by lucas-wilkins** [comment]
Ah, looks like its being published and deleted. Following the link in the installer script.

**Comment by krzywon** [comment]
At the top, look for job runs. The Mac installer is in the first run.

**Comment by lucas-wilkins** [comment]
I'd say both mac and windows are good to go!

**Comment by krzywon** [comment]
I also tested both Mac builds on a Silicon based Mac. They both load, though the Intel-based build does take a while to load the first time. I'm going ahead and merging this and will have RC2 available once the merged build is finalized.

**Pull request merged**
