### PR TITLE
Add Compute Button and Limit Fitting Computations

### PR DESCRIPTION
**Pull request by krzywon**
This PR adds a 'Compute' button to fit pages and limits recalculation to when the user presses this button, or hits the Enter or Return keys. This matches the behavior in 4.2.2.

Refs #1767

### CODE REVIEW

**Comment by butlerpd** [comment]
Plot does the same thing as compute currently  we should consolidate this and use a better button name
call it plot/update and add a tooltip

**Comment by butlerpd** [comment]
ready for testing on Win

**Comment by butlerpd** [comment]
ready for testing on Win

**Review by butlerpd — CHANGES_REQUESTED** [review]
I can confirm that compute/show now exists and works. However the `CR` key (or enter) does nothing despite the advertisement. Wondering if the problem is that the code only "recalculates plot data" but doesn't force a replot of that data?  At any rate the enter key not working needs to be fixed I guess before we can merge.

**Comment by butlerpd** [comment]
another question: If the model is already calculated (as it is to start with) does the button force a recalculation anyway?

**Comment by krzywon** [comment]
> If the model is already calculated (as it is to start with) does the button force a recalculation anyway?

Yes.

> However the `CR` key (or enter) does nothing despite the advertisement.

Testing the PR build, I can trigger a recalculation, but only when the data is already plotted and when the Fit panel has focus. I agree this should generate a new plot if one isn't present already but the fitting perspective should not capture the Enter key anytime it wants.

**Comment by butlerpd** [comment]
Humm... I think we are saying the same thing?  To be clear, from my dumb user perspective, I enter a new value for one of the parameter and hit enter and absolutely nothing happen!! I think what you are saying is that it does "recalculate" which is what the code looks like it is doing.  But  I was unable to figure anyway to get the plot to update (the only recalculate that I ever see and thus that matters to me 😄 ) after entering a new value other than hitting the computer button.  I think we agree that hitting the enter key from random places should not trigger a "recalculate" ... and by "recalculate," as a user, I mean recalculate and re-plotted.

Is this the  behavior you get? Or are you saying you actually get it to replot properly when entering a value followed by a return?

**Comment by krzywon** [comment]
> Is this the behavior you get? Or are you saying you actually get it to replot properly when entering a value followed by a return?

One other thing I see now - if you are editing a parameter (cursor in the param value box), the enter key exits the input box without an update. Another enter keypress is needed. The 1st enter should do both.

Things I need to fix:
- Enter/CR keys should generate a new plot if one isn't already plotted.
- Enter/CR keys should generate a calculation while editing a parameter.

**Comment by butlerpd** [comment]
Ahhh.  You have to press CR twice to get it to plot the new curve.  That is one thing I did not try :-)  Yes one time should do it (exit the box and update the data/plot as you exit).

**Comment by krzywon** [comment]
My latest changes should fix both of these now.

> Things I need to fix:
> - Enter/CR keys should generate a new plot if one isn't already plotted.
> - Enter/CR keys should generate a calculation while editing a parameter.

**Comment by krzywon** [comment]
ready for testing on Win

**Review by butlerpd — APPROVED** [review]
The PR now behaves as advertized.  The code seems reasonable to the untrained eye given the rather convoluted behavior that is given to the `compute/plot` button.  I think that button behavior could be improved from the point of view of a researcher wanting to fit data and if that change is made there may be some code simplification possible.

That however is another ticket.  In the meantime I believe this can be merged

**Pull request merged**
