### PR TITLE
Added 3.11, removed 3.8

### PR DESCRIPTION
**Pull request by rozyczko**
## Description

Removed 3.8 and added 3.10, 3.11 to build/test matrix
Removed pinned versioning which caused issues with 3.11

Local win10 dev build and installer

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [X] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked)

### CODE REVIEW

**Comment by llimeht** [comment]
Would `np.float64` be better to be explicit about the precision? Probably makes no real difference unless someone is marshalling this through C somewhere.
https://sources.debian.org/src/sasview/5.0.5-5/debian/patches/numpy-1.24.patch/

This work should also close #2416.

**Comment by rozyczko** [comment]
> Would `np.float64` be better to be explicit about the precision? Probably makes no real difference unless someone is marshalling this through C somewhere. https://sources.debian.org/src/sasview/5.0.5-5/debian/patches/numpy-1.24.patch/
> 
> This work should also close #2416.

Shouldn't make a difference, since the built-in float is dp anyway on non-32 bit arch.
It might be useful to have it spelled out explicitly, maybe, so let's do it then.

**Comment by wpotrzebowski** [comment]
I was curious if OSX installer works on 3.11 and it seems to work fine!

**Comment by butlerpd** [comment]
Not sure we need all 3 python versions. Maybe focus on 3.11 and try to make sure everything works there.  Needs lots of testing.  Aim to merge prior to code camp to ensure fulsome testing.

**Comment by rozyczko** [comment]
> Not sure we need all 3 python versions. Maybe focus on 3.11 and try to make sure everything works there. Needs lots of testing. Aim to merge prior to code camp to ensure fulsome testing.

Good catch. We only need one python version for the release (3.11) but we want testing to be done on all supported versions (3.8, 3.9, 3.10, 3.11)

**Comment by wpotrzebowski** [comment]
The installer starts on Mac, however, it crashes whenever I try to access any folder

`Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
Fatal Python error: PyGILState_Release: thread state 0x1026663a8 must be current when releasing
Python runtime state: initialized
`

**Review by wpotrzebowski — APPROVED** [review]

**Pull request merged**
