### PR TITLE
Pull request template

### PR DESCRIPTION
**Pull request by wpotrzebowski**
As discussed at the code camp X some checklist for the PRs may be useful.

Here is a suggestion for PR template (inspired by https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/):

## Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes # (issue/issues)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by smk78 — CHANGES_REQUESTED** [review]
Nice. And rigorous. :-)

Some other typos that need correction:
 - Author checklist, bullet 5: should be 'locally'
 - Author checklist, bullet 6: probably should say 'with our BSD'?
 - Review checklist, bullet 1: probably should be 'reviewed'
 - Review checklist, bullet 3: probably should _either_ say 'install and work' _or_ 'installed and worked'

And two comments:
 - Should there be something to cover a case where no documentation is actually required (as opposed to not checking the box which just suggests none has been done)?
 - Should there be something to capture what platform the installer(s) have been tested on?

**Review by butlerpd — COMMENTED** [review]
regarding N/A buttons they could be rewritten to say :xx was done if applicable.  Then checking it just means that you thought about it and either did it or decided nothing was needed?

Does "fixes" close the issue when merging to main? or do you need to use "closes"

Otherwise looks good though the description of what is needed in the narration may sound a bit scary to a new comer?

**Comment by wpotrzebowski** [comment]
I thought one can delete these items that are not applicable (check updated version)
I doubt "fixes" closes the issue  upon merging.

**Review by butlerpd — APPROVED** [review]
looks good to me now. Fixes should work to close things it turns out. Removing the author check list makes it much more approachable

**Review by smk78 — APPROVED** [review]
I'm quite happy to endorse this now much slimmed down template which nonetheless should still capture the essential information required.

**Pull request merged**
