### PR TITLE
File loader enhancement of the General Scattering Calculator

### PR DESCRIPTION
**Pull request by dehoni**
This PR improves the data load routine that is used to read omf, and pdb files in the general scattering calculator.

### CODE REVIEW

**Comment by rozyczko** [comment]
> Sorry, the file was missing the magnetisation unit value. It is fixed and should work now.

Thanks! Can you please attach the file? I can't find its location anymore :/

**Comment by dehoni** [comment]
The test file is attached to the ticket https://github.com/SasView/sasview/issues/1826 .

**Review by rozyczko — APPROVED** [review]
This indeed helps A LOT with loading large OMF files. As in, order of magnitude.

The code, as mentioned, looks good.

**Comment by dehoni** [comment]
The error message "We accept only Text format OMF file" was rather cryptic. The file is a text but the physical units are missing. The commit returns now a more sensible error.

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Pull request merged**
