### PR TITLE
Github actions for OSX build

### PR DESCRIPTION
**Pull request by wpotrzebowski**
This PR primarily address OSX installer issues including code sigining and notarization. Code sigining and notarization is moved to release.yml file as it is not feasible to do it for each push (code sigining can be done as it takes little time but it is more logical to keep it as a release). 

I've managed to make it working with python 3.8 only and there are some hacks in sasview.spec file related to this. It would be good to get rid of this dependency but it doesn't seem to be easy...

This PR should also address issues with plotting (nonposy issue with recent mpl version) and missing documentation.

### CODE REVIEW

**Comment by rozyczko** [comment]
ready for testing on Win

**Comment by rozyczko** [comment]
ready for testing on Win

**Comment by rozyczko** [comment]
ready for testing on Win

**Comment by rozyczko** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Pull request merged**
