### PR TITLE
Slicer editor with checkbox

### PR DESCRIPTION
**Pull request by rozyczko**
Currently used for `fold`.
Separate commit to the number of points validator fix, both need to be merged.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Review by wpotrzebowski — APPROVED** [review]
Code looks good. Leaving functionality test to @butlerpd

**Comment by butlerpd** [comment]
ready for testing on Win

**Comment by butlerpd** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win

**Review by butlerpd — APPROVED** [review]
code looks right.  I can no longer get it to throw errors when playing with the boxslicer and editor. In particular I cannot cause the failure reported in #1766.  Good to merge

**Comment by krzywon** [comment]
> code looks right. I can no longer get it to throw errors when playing with the boxslicer and editor. In particular I cannot cause the failure reported in #1766. Good to merge

@butlerpd did you mean to comment on #1768? This one sets fold to a boolean.

**Comment by butlerpd** [comment]
LOL ..yes I clearly put it in the wrong place @krzywon.  Sorry @rozyczko.  I also meant to comment on this which works as advertized and **much** nicer that before. I was confused by the code though as it seemed like it was missing something and I was trying to understand why I was wrong and got distracted.  Anyway, it is now merged so all good 👍

**Pull request merged**
