### PR TITLE
Deleted src/sas/sasgui #1582

### PR DESCRIPTION
**Pull request by rozyczko**

### CODE REVIEW

**Comment by pkienzle** [comment]
It looks like sas.sasview should also be removed/restructured.  It is mostly used for `__version__` and `__build__` symbols, but these can be moved to the `sas` directory. The directory of example data needs to move somewhere; maybe `src/sas/data` (look into pkgutil.get_data() for accessing it). The `custom_config.py` file can move into the qt gui directory.

The failing test is using Data1D/Data2D from sasgui.  It should be able to pull these symbols from sascalc directly.

Side note: after splitting sascalc into its own package, promote `sas.qtgui` to `sasview` and drop the `sas` namespace. 

```
~/Source/sasview:ESS_GUI_deleted_sasgui $ grep "sasview[.]" src/**/*.py | grep -v sasmodels | grep -v sasview.org
src/sas/_config.py:    application this will be the directory containing sasview.py.  For the
src/sas/_config.py:    logger.info("GuiManager custom_config defaults to sas.sasview.custom_config")
src/sas/logger_config.py:    Called at the beginning of run.py or sasview.py
src/sas/qtgui/MainWindow/AboutBox.py:        version = sas.sasview.__version__
src/sas/qtgui/MainWindow/WelcomePanel.py:        version = sas.sasview.__version__
src/sas/qtgui/MainWindow/WelcomePanel.py:        build = sas.sasview.__build__
src/sas/qtgui/Utilities/GuiUtils.py:    # that can be passed by sasview.py.
src/sas/qtgui/Utilities/GuiUtils.py:    app_path = os.path.dirname(sasview.__file__)
src/sas/qtgui/Utilities/LocalConfig.py:__version__ = sas.sasview.__version__
src/sas/qtgui/Utilities/LocalConfig.py:__build__ = sas.sasview.__build__
src/sas/qtgui/sasview/local_config.py:__version__ = sas.sasview.__version__
src/sas/qtgui/sasview/local_config.py:__build__ = sas.sasview.__build__
src/sas/sasview/local_config.py:__version__ = sas.sasview.__version__
src/sas/sasview/local_config.py:__build__ = sas.sasview.__build__
~/Source/sasview:ESS_GUI_deleted_sasgui $ grep sasview src/**/*.py | grep import | grep -v sasmodels        
src/sas/_config.py:    from sas.sasview import custom_config
src/sas/qtgui/MainWindow/AboutBox.py:import sas.sasview
src/sas/qtgui/MainWindow/WelcomePanel.py:import sas.sasview
src/sas/qtgui/Perspectives/Fitting/ReportPageLogic.py:from sas.sasview import __version__ as SASVIEW_VERSION
src/sas/qtgui/Plotting/AddText.py:import sas.sasview
src/sas/qtgui/Plotting/ScaleProperties.py:import sas.sasview
src/sas/qtgui/Utilities/GuiUtils.py:    from sas import sasview as sasview
src/sas/qtgui/Utilities/LocalConfig.py:import sas.sasview
src/sas/qtgui/sasview/local_config.py:import sas.sasview
src/sas/sascalc/fit/pagestate.py:from sas.sasview import __version__ as SASVIEW_VERSION
src/sas/sasview/local_config.py:import sas.sasview

```

**Comment by pkienzle** [comment]
Can also branch wxgui off master and pull ESS_GUI into master to further reduce confusion.  The build and release systems will of course need to be updated for this, so perhaps a separate ticket.

**Comment by rozyczko** [comment]
Yes, `sasview` is going away next. As you noticed, there are still a few trivial dependencies, but I'll remove them as part of another ticket/effort

**Comment by rozyczko** [comment]
merging/substituting `master` with `ESS_GUI` is also coming.
Unless we will be forced to replace `master` with `main` in which case we'll just rename `ESS_GUI`

**Comment by rozyczko** [comment]
Let's not merge this for 5.0.3 - there's more work involved and it would be indeed good to delete `sasview` directory as well.

**Comment by pkienzle** [comment]
#1599 should fix the failing tests.

The classes in `qtgui/Plotting/PlotterData` should be updated to remove the methods duplicated from the parent class.

**Comment by pkienzle** [comment]
The failing test will go away once the merge is complete. The ESS_GUI branch moved the data operations tests to use the base classes in sascalc rather than the classes in sasgui. The qtgui data classes still need to be updated to use the sascalc data structures directly rather than reimplementing them, but that can be done in a separate PR.

**Pull request merged**
