### PR TITLE
2914: Display messages to show project file is loading

### LINKED ISSUE #2914: Not apparent anything is happening when opening a project
**Describe the bug**
Opening a project with a lot of loaded data can take many seconds. During this time there is no indication that anything is happening, other that on Win you get the little revolving blue circle.

### PR DESCRIPTION
**Pull request by krzywon**
## Description

This displays a message while a project file is loading. I'm not convinced this should be for 6.0.0, but it is a small change.

Fixes #2914

## How Has This Been Tested?

Tested locally and from the push installer (Windows)

## Review Checklist:

**Documentation** (check at least one)
- [x] There is **nothing** that needs documenting
- [ ] Documentation changes are **in this PR**
- [ ] There is an **issue** open for the documentation (link?)

**Installers**
- [x] There is a chance this will affect the **installers**, if so
  - [ ] **Windows** installer (GH artifact) has been tested (installed and worked) 
  - [ ] **MacOSX** installer (GH artifact) has been tested (installed and worked) 

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by wpotrzebowski — APPROVED** [review]

**Review by rozyczko — APPROVED** [review]
Works well. Code looks OK.
A bit puzzled with `\n` - most messages emited don't have the carret return.
This will probably cause the status bar to change the height?

**Comment by krzywon** [comment]
> A bit puzzled with `\n` - most messages emited don't have the carret return. This will probably cause the status bar to change the height?

I just removed them

**Comment by rozyczko** [comment]
> carret return.

Did I say `carret`? lol. At least not `carrot return`...

**Comment by krzywon** [comment]
> > carret return.
> 
> Did I say `carret`? lol. At least not `carrot return`...

:rabbit: :carrot:

**Review by smk78 — COMMENTED** [review]
Tested actions build 10510126482 for functionality on W10/x86 with a dummy project using the infamous VMTA dataset.
Lovely! Puts a message in the status bar that says the project is loading, which changes to Project loaded when complete.

**Pull request merged**
