### PR TITLE
2414 move qtgui to sasview

### PR DESCRIPTION
**Pull request by lucas-wilkins**
## Description

Moved files from qtgui to sasview

## How Has This Been Tested?

Still runs, installers need checking.

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by rozyczko** [comment]
Apart of failing tests, there seem to be more places with unchanged string
1. icons in
`src\sas\sasview\Perspectives\Fitting\FittingPerspective.py`
line 264: `icon.addPixmap(QtGui.QPixmap("src/sas/qtgui/images/icons/layers.svg"))`
line 286: `icon.addPixmap(QtGui.QPixmap("src/sas/qtgui/images/icons/link.svg"))`

2. all references to html files with `/user/qtgui` path segment

it doesn't help that QtGui is also the name of a PyQt5 module used heavily throughout the code...

**Comment by lucas-wilkins** [comment]
> Apart of failing tests, 

CI tests are fine apparently.

> there seem to be more places with unchanged string

Think I've got them all now.

**Comment by lucas-wilkins** [comment]
The tests are passing.

I thought I'd got them all.

**Comment by lucas-wilkins** [comment]
Open for too long, avoiding merge conflict hell...

**Pull request closed without merging**
