### PR TITLE
Updated rG&rg

### PR DESCRIPTION
**Pull request by smalex-z**
## Description

Upon discussion with @butlerpd @pkienzle and @yunliu01, we decided it would be best to make the difference between Mass Based Radius of Gyration (Rg) and SLD Based Guinier Radius (RG) more obvious. I have separated the radius of gyration into two boxes, one for Mass-Based and one for SLD-Based.

I have also included code to change the SLD-Based RG based on the Solvent SLD, but that is commented out until a standard for determining protein volume can be agreed upon.

## How Has This Been Tested?

Open Generic Scattering Calculator

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by krzywon — COMMENTED** [review]
A couple of suggestions to clean up the code, but nominally does what it says it does. I can't speak to the accuracy, because no documentation was added for the calculation being performed.

**Comment by butlerpd** [comment]
This pull request and #2538 should be reviewed and hopefully approved but should d to wait be merged into one big pull request to resolve all the UI conflict and that pull request then merged. To avoid confusion I'm labeling this as WIP

**Comment by pkienzle** [comment]
These changes are mostly repeated in #2565. Review and merging will be easier if you combine them into one PR, or base one PR off the other.

**Comment by smalex-z** [comment]
This PR and #2538 is not supposed to be merged- the changes are all repeated in #2565 because of merge conflicts with UI files. Once all 3 PRs are approved, only #2565 will be merged into main with the changes from all 3 PRs.

**Comment by butlerpd** [comment]
@krzywon can this branch now be safely deleted? I think this is the other PR that was merged into a bigger one before closing?

**Pull request closed without merging**
