### PR TITLE
[Release 5.0.6] Master 5.0.6 release PR

### PR DESCRIPTION
**Pull request by krzywon**
This PR cherry-picks most/all of the plotting fixes we plan to include in v5.0.6.

- #2099
- #2266
- #2293 
- #2298 
- #2300 
- #2329 
- #2362

### CODE REVIEW

**Comment by caitwolf** [comment]
I added cherry-picks for the following PRs as part of the 5.0.6 release:

- #2318 
- #2331 
- #2336 
- #2338

**Comment by wpotrzebowski** [comment]
I haven't tested this version extensively but copying parameters to LATEX and Excel doesn't seem to work:
`15:22:07 - ERROR: Traceback (most recent call last):
  File "sas/qtgui/Perspectives/Fitting/FittingPerspective.py", line 123, in onLatexCopy
  File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 3896, in onCopyToClipboard
  File "sas/qtgui/Perspectives/Fitting/FittingUtilities.py", line 863, in formatParametersLatex
IndexError: list index out of range`

**Comment by krzywon** [comment]
> I haven't tested this version extensively but copying parameters to LATEX and Excel doesn't seem to work: `15:22:07 - ERROR: Traceback (most recent call last): File "sas/qtgui/Perspectives/Fitting/FittingPerspective.py", line 123, in onLatexCopy File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 3896, in onCopyToClipboard File "sas/qtgui/Perspectives/Fitting/FittingUtilities.py", line 863, in formatParametersLatex IndexError: list index out of range`

@wpotrzebowski - #2369, opened by @smk, seems to be a similar, if not the same, issue.

**Comment by wpotrzebowski** [comment]
> > I haven't tested this version extensively but copying parameters to LATEX and Excel doesn't seem to work: `15:22:07 - ERROR: Traceback (most recent call last): File "sas/qtgui/Perspectives/Fitting/FittingPerspective.py", line 123, in onLatexCopy File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 3896, in onCopyToClipboard File "sas/qtgui/Perspectives/Fitting/FittingUtilities.py", line 863, in formatParametersLatex IndexError: list index out of range`
> 
> @wpotrzebowski - #2369, opened by @smk, seems to be a similar, if not the same, issue.

Thanks @krzywon for pointing this out. In my case it didn't work with core shell model. I need to check if it is model dependent and more importantly in the context of 5.0.6 is it also a bug in 5.0.5.

**Comment by krzywon** [comment]
> Thanks @krzywon for pointing this out. In my case it didn't work with core shell model. I need to check if it is model dependent and more importantly in the context of 5.0.6 is it also a bug in 5.0.5.

The second comment in the ticket mentions it applies to **all** multiplicity models, not just `unified_power_rg`. I'm updating the title now for clarity.

**Review by butlerpd — APPROVED** [review]
This PR just cherry picks a number of agreed upon commits to main which were already tested and code reviewed.  Thus I think we should approve the merge and test the release branch as a whole to make sure none of these are relying on changes not picked.

**Pull request merged**
