### PR TITLE
Testing nightly build

### PR DESCRIPTION
**Pull request by wpotrzebowski**
## Description
The action triggers main CI job (ci.yml), renames artifacts files, notarizes OSX artifact and uploads to https://github.com/SasView/sasview/releases/tag/nightly-build.  Code signing for Mac is done in ci.yml as it was difficult to sign dmg (rather than app file). The action should be triggered whenever there is a push to main branch, otherwise ci.yml should work as usual.

Fixes # (issue/issues) #2466

## How Has This Been Tested?

Download artifact from https://github.com/SasView/sasview/releases/tag/nightly-build and test if it works

## Review Checklist (please remove items if they don't apply):

- [x] Code has been reviewed
- [x] Functionality has been tested
- [x] Windows installer (GH artifact) has been tested (installed and worked) 
- [x] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [x] User documentation is available and complete (if required)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by butlerpd** [comment]
almost all actions today were hanging on the ubuntu 20.04python3.8 at the cylinder model of the bumps/sasmodels docs build. I cancelled that workflow here after ~ 3.5 hours. I'm hoping it is just a function of a lot of activity being pushed today?

**Comment by lucas-wilkins** [comment]
> almost all actions today were hanging on the ubuntu 20.04python3.8 at the cylinder model of the bumps/sasmodels docs build.

I have noticed that, it seems to be consistent, see #2460

**Comment by butlerpd** [comment]
> I have noticed that, it seems to be consistent, see #2460

Indeed I saw that and was going to add to that issue but wanted to document that I'd aborted that workflow. Indeed with nothing else hanging or running my other one finally got through everything and is seems so did this though I did no relaunch it?  It does seem to do with load on the system though?

**Comment by wpotrzebowski** [comment]
@lucas-wilkins: we should be able to provide nightly builds through this link: https://github.com/SasView/sasview/releases/tag/nightly-build. The link should be accessible to people from outside the sasview organization. I need to still work out some details in GH action.

**Comment by lucas-wilkins** [comment]
@wpotrzebowski Nice. Is it scheduled with a cron job? Or does it just happen when things are pushed?

**Comment by lucas-wilkins** [comment]
Would this work perhaps?

```
on:
  push:
    branches:
      - 'main'
  ```

**Comment by wpotrzebowski** [comment]
Need to close this and reopen this PR as apparently labels are not respected.

**Comment by wpotrzebowski** [comment]
The proposed mechanism is based on "nightly-build" label. Simply if the label is set up for PR artifact will be uploaded to the release page, if not then nothing happens. This way we have more control over what should go into the release page and also tests should pass for those forking from outside.

**Comment by lucas-wilkins** [comment]
I'm being picky, but can we capitalise and space the label, i.e. "Nightly Build"? So it's in keeping with the other labels.

**Comment by lucas-wilkins** [comment]
@wpotrzebowski I've found a problem with this method, github doesn't allow pull requests from branches that do not differ in contents from main. So, it is impossible to make a 'nightly build' of the current main branch.

**Comment by wpotrzebowski** [comment]
Indeed, this will work for newly created PRs only and it will overwrite release whenever a new PR is created. This is probably not what we want. I will try to implement cron job for main branch.

**Comment by lucas-wilkins** [comment]
Does it work?!

**Comment by wpotrzebowski** [comment]
@lucas-wilkins Nope, and requires somewhat more work (therefore I am reopening PR in draft mode).

**Comment by wpotrzebowski** [comment]
I can in principle copy/paste entire ci.yml file to nightly_build.yml and run it as a cron job or on push to main, however, I would rather prefer to avoid workflow duplications. Therefore I am exploring reusable github workflows, however without much success yet.

**Comment by butlerpd** [comment]
@krzywon to merge unless he finds a show stopper

**Review by krzywon — APPROVED** [review]

**Pull request merged**
