### PR TITLE
Ticket 639 katex

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Not fully ready yet for merging with master but want to build it on VM using githun pull request builder

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by celinedurniak** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Pull request merged**
