### PR TITLE
Generic scattering calculator C conversion 4.x

### PR DESCRIPTION
**Pull request by pkienzle**
Like #1403 but applies to the 4.x branch.  This removes the last bit of C code.

The calculator has been checked against the ellipsoid model, 1D, 2D and magnetic.

The magnetic model will return different results since the top of the sample is not oriented toward the beam to correspond to the analytical calculations in sasmodels. Furthermore, the C code had my and mz swapped when calling the calculator.

The is_avg flag does not work for particles without spherical symmetry. This option will need to be removed in the GUI. See #1400.

### CODE REVIEW

**Comment by pkienzle** [comment]
Note: oommf and debye avg. are failing in the wx gui, so not yet ready for review.

**Comment by pkienzle** [comment]
oommf and debye avg are now fixed.  Ready for review.

**Comment by pkienzle** [comment]
If this PR includes the changes from #1404.  If it is merged then #1404 can be deleted.

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Review by wpotrzebowski — APPROVED** [review]

**Pull request merged**
