### PR TITLE
Corfunc3d

### PR DESCRIPTION
**Pull request by pkienzle**
Calculate the 3D correlation function and IDF

Closes ticket #784

### CODE REVIEW

**Comment by pkienzle** [comment]
Note: tests should be updated to check the new functionality.

**Comment by pkienzle** [comment]
I replaced the iterated call to trapz with a call to cumtrapz.  Since the corfunc3d features are not being tested, I don't know if this breaks anything.

**Comment by smk78** [comment]
Just tested this. It is throwing an error when it tries to plot the 3d function:

Plotting Error: Plottable.View: Given y and x are not of the same length

Attached file has lewis' trapz version on the left, and pkienzle cumtrapz on the right.
corfunc3d-lews-vs-paulk

**Comment by butlerpd** [comment]
I don't understand this -- am I reading right that using the trapz function does not throw an error while using cumtrapz fails because of a data error (q and i arrays are of different length)?

**Comment by smk78** [comment]
Yes, butler of, that is what is currently happening.

**Comment by smk78** [comment]
Sorry, replace 'butler of' by 'butlerpd' in previous comment! Autocorrect!

**Comment by smk78** [comment]
ready for testing on osx

**Comment by smk78** [comment]
On advice from pkienzle am merging this branch now. With the caveat that unit tests for the corfunc perspective are currently disabled because of precision issues. This is noted for future action in #998

**Pull request merged**
