### PR TITLE
Ticket 1032 sldi

### PR DESCRIPTION
**Pull request by pkienzle**
The generic scattering calculator now runs again after a py3 conversion error.   The code has been converted from C++ to C so that work can begin on tinycc support for windows.

The test suite now includes a simple smoke test to check that it indeed runs without crashing, but the return value is not checked, and it is not tested against the different types of inputs (1d, 2d averaged, 2d).  Ticket 1033 requests proper test cases.

### CODE REVIEW

**Comment by smk78** [comment]
As I understand the purpose of the requested review, it is to check that changes made to C code to enable us to use the TinyCC compiler in the future have not caused retrospective issues with BSL file support.

So have built SasView branch ticket 1032 on Win 7 within ORIGINAL Anaconda environment (ie, not the new one developed at the recent Code Camp) using 32-bit gcc compiler.

At start of the build I get (my bolding)

10:35:17 - DEBUG : __main__: 185: Starting SASVIEW in debug mode.
running build
running build_py
**package init file 'src\sas\sascalc\dataloader\readers\schema\__init__.py' not found (or not a regular file)**
running build_ext
**error: don't know how to compile C/C++ code on platform 'nt' with 'tinycc' compiler**
10:35:19 - INFO : sas.sasview.sasview: 138:  --- SasView session started ---

but the build completes and SasView runs. A fit to a test dataset executed as expected.

Attempting to Load Data Z83000.l1D (BSL) from the \test\convertible_files folder fails as it should do.

Running the File Converter on the same file (selecting BSL 1D) completed as expected and generated xml output that loaded ok through Load Data and displayed.

Ran the File Converter on a Diamond I22 multi-frame 2D BSL dataset. Also completed as expected and generated h5 output that loaded ok through Load Data and was rendered correctly as 2D images.

**Comment by pkienzle** [comment]
Please install tinycc into your environment using  ```pip install tinycc```. Then remove the "build" directory and try ```run.py``` again.

The following error **should not** appear:
```
error: don't know how to compile C/C++ code on platform 'nt' with 'tinycc' compiler
```
You can ignore the other error for now.

Can you add tests for the bsl converter into the tests directory if they are not already there?

**Comment by smk78** [comment]
pip installed tinycc-1.1 as requested and recompiled.

Console now reports (my bolding)

15:26:52 - DEBUG : __main__: 185: Starting SASVIEW in debug mode.
running build
running build_py
**package init file 'src\sas\sascalc\dataloader\readers\schema\__init__.py' not found (or not a regular file)**
running build_ext
**Compiling with tinycc (64bit=False)**
15:26:54 - INFO : sas.sasview.sasview: 138:  --- SasView session started ---

which I interpret as good news?

Running the File Converter on Z98000.l1D this time (selecting BSL 1D) completed as expected and generated xml output that loaded ok through Load Data and displayed.

**Comment by smk78** [comment]
Added xml conversions of 1D BSL files Z83000.l1D and Z98000.l1D to \tests\convertible_filees folder for possible use as unit tests.

**Comment by pkienzle** [comment]
I added a ticket for the BSL test so that we can merge this pull request.

**Pull request merged**
