### PR TITLE
FIX: fix model date format in the user model docstring

### PR DESCRIPTION
**Pull request by mrakitin**
## Description

This PR fixes the date format appearing in the "Authorship and Verification" section of the generated user model. Before the fix, the dates were displayed as `2024YYY-01m-16d`. After the fix, they look like: `2024-01-16`.

It's part of the https://github.com/SasView/sasview/wiki/ContributorCampXII camp.

Fixes # (issue/issues)

## How Has This Been Tested?

The fix was tested by comparing the output of the generated models before (with v6.0.0-alpha1) and after the fix.

### Before:
image

### After:
image

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by wpotrzebowski — APPROVED** [review]
Code looks good. The reason why Mac installer is failing is lack to acceess to certifcates when forking. (Somethinig I tried to fix before the contributor camp but failed).

**Comment by wpotrzebowski** [comment]
> Thanks for your review, @wpotrzebowski! Is the target branch (`main`) fine? Or should I retarget it to `release_6.0.0`?

Good point! We will need it for both but please rebase to 6.0.0 for now and then we will merge to main (after release I suppose)

**Comment by mrakitin** [comment]
OK, I rebased my commit on the `release_6.0.0` (checked out fresh from the `release_6.0.0` branch and cherry-picked the `9ee2283b75265c024f2ce685842224bafeac4845` commit).

**Comment by wpotrzebowski** [comment]
I am merging this PR even though it fails. However it fails because it is opened as a fork and cannot upload artifacts.

**Comment by mrakitin** [comment]
Thank you, @wpotrzebowski!

**Pull request merged**
