### PR TITLE
Quote file names in ConvertUI

### LINKED ISSUE #2791: Installation sasview developers_Convert UI does not create output if a space is present in thefolder name in the path
**Describe the bug**
During the installation of sasview developers enviroment, this kind of error was happaneng (see picture below):

**To Reproduce**

**Expected behavior**

**Screenshots**

**SasView version (please complete the following information):**
 - Version: [e.g. 5.0.4]

**Operating system (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

### PR DESCRIPTION
**Pull request by MariannaGerina**
## Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
Fixed issue: convertUI does not create a outfiles when a space is present in a folder of the path. The issue was fixed properly quoting the files name in the convert UI.
Fixes #2791 

## How Has This Been Tested?
After this change,  run.py can start the application

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Comment by llimeht** [comment]
Good catch, and I suspect there are others like this elsewhere in the code.

Trying to robustly quote filenames will always be problematic (what happens if my directory name has a " in it?) and `os.system` passes the command through a subshell which can do odd things too (what if the directory name has a $ or \` in it?). `os.system` also look after the output (just gets dumped to the terminal, probably not an issue for these uses). The current code also doesn't check that the operation succeeded, which it really should.

Rather than trying to quote filenames to put them in a string and give them to `os.system` so that the shell can then try to split the string back up and then execute the command, how about putting the command into a `list` and giving it directly to `subprocess.run`. This has the benefit that the command doesn't get interpreted by a shell (with the default `shell=False`) so no quoting is needed. Additionally, output is easily captured, and it can raise an exception on failed operations.

[https://docs.python.org/3/library/subprocess.html#subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run)

**Comment by butlerpd** [comment]
I think this should be against 6.0.0 not main. Particularly given the comments by @llimeht who points out that this is a tiny band-aid for a much larger problem than continuously bites us.  However his suggestion seems like it will require skills beyond mine or the author's and the question is whether anybody else will be able to address this "properly" in the near future? If not I would recommend we merge this into 6.0.0 and create an issue with @llimeht suggestions given it fixes a problem we had at the contributor camp?

**Comment by butlerpd** [comment]
@lucas-wilkins suggests fixing the way @llimeht suggests but only for this issue before merging "should not be hard to do" - but says it is better than no change.

**Comment by butlerpd** [comment]
@lucas-wilkins suggests this will be "easy" ... looking this up and reading a bit about it do you mean we should replace
```python
run_line = f"pyside6-rcc {in_file} -o {out_file}"
os.system(run_line)
```
with
```python
run_line = ["fpyside6-rcc", in_file, "-o" ,out_file]
subprocess.run(run_line)
```
??
It doesn't seem like any of the kwargs are necessary here? all defaults should be good?
This seems a bit scary to a white belt like me?

**Comment by butlerpd** [comment]
OK thanks ... I'll give it a go then

**Pull request merged**
