### PR TITLE
2798 saving project with the general scattering calculator throws an error

### LINKED ISSUE #2798: Saving Project with the general scattering calculator throws an error
**Describe the bug**
Reported by user Sabol-Pulling.

> Whenever I try to save my sasview window as a json project file after using the generic scattering calculator I get the following error:

```
  File "sas\qtgui\MainWindow\GuiManager.py", line 711, in actionSave_Project
  File "sas\qtgui\Utilities\GuiUtils.py", line 1279, in saveData
  File "json\__init__.py", line 179, in dump
  File "json\encoder.py", line 431, in _iterencode
  File "json\encoder.py", line 353, in _iterencode_dict
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
**To Reproduce**
I reproduced the error using 6.0.0 alpha1 as follows:
1. bring up the Generic Scattering Calculator
2. Load pdb file (I used dna)
3. Click on "Compute Debye full average
4. See plot show up on SasView canvas
5. Go to File -> Save Project
6. See error

**Expected behavior**
The general scattering calculator is a tool and therefore does not have a "save state." However SasView should save the sate of all open perspectives, or if none, state there are none to save, but should not throw a traceback error

**SasView version (please complete the following information):**
 - Not sure what version the user was using, presumably 5.0.6 or less.
 - My test used 6.0.0a1

**Operating system (please complete the following information):**
 - OS: Windows 10 Enterprise for my test. Not sure what the user had

### PR DESCRIPTION
**Pull request by rozyczko**
## Description

The Data object needs the .id field to be serializable. Added this to GSC generated data.
Also, improved our json serialized to handle DataRole enums as it was not saving these for the GSC data.

Fixes #2798

## How Has This Been Tested?

Local win10

## Review Checklist:

**Documentation** (check at least one)
- [X ] There is **nothing** that needs documenting
- [ ] Documentation changes are **in this PR**
- [ ] There is an **issue** open for the documentation (link?)

**Installers**
- [ ] There is a chance this will affect the **installers**, if so
  - [ ] **Windows** installer (GH artifact) has been tested (installed and worked) 
  - [ ] **MacOSX** installer (GH artifact) has been tested (installed and worked) 

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

### CODE REVIEW

**Review by krzywon — APPROVED** [review]
This appears to fix the project save issue. 

I'm having issues with the file browser as noted in https://github.com/SasView/sasview/pull/2877#discussion_r1611157461. I plan to implement that change for all file dialogs.

**Review by butlerpd — CHANGES_REQUESTED** [review]
How did you test @krzywon? From the installer or your workspace?
I just downloaded the windows artifact and ran from the installer and still see the error?

I do note however that the CI  (under summary) is reporting a error on the windows 3.11 installer of `Couldnt find the Android build tools @ C:\Android\android-sdk\build-tools\30.0.2`  It also gives a warning that it cannot find the mag OS dmg file and thus "not uploading the artifact?"

I'm not sure these errors however would be causing the problem? unless it is posting an old windows artifact for download?

**Comment by butlerpd** [comment]
BTW - I believe this is the correct approach now that the GSC is mingling with the real perspectives and the data manager. However I note that none of the tools I tried will save to project, they just throw an `Info` warning that the data cannot be serialized:
`INFO: data cannot be serialized to json: `

This includes the image viewer which also adds a data file to the data manager when clicking `convert`. The problem with the GSC is it is throwing an error.

**Comment by rozyczko** [comment]
This worked for me from the installer from the PR build page.

https://github.com/SasView/sasview/actions/runs/9920007759?pr=2955

**Comment by krzywon** [comment]
@butlerpd - I just tested the installed version, followed the steps outlined in #2798 and am no longer seeing an error when saving a project.

**Comment by butlerpd** [comment]
OK .. I'll re-download the installer and try again. Sorry if I somehow got confused on what artifact I was using.

**Comment by butlerpd** [comment]
Done and still has the error. 

Checking w/ @krzywon,  he was not checking with the `Debye full avg` as described in issue #2798 but was using the `Fixed orientation` 2D calculation.  Apparently these are different?

Not sure if this is due to different data objects (1D vs 2D) or different paths taken but the result at this point is that it is now working for 2D but is still throwing the error in the more generally used 1D.

**Comment by rozyczko** [comment]
Thanks for testing @butlerpd. This should be fixed now. Both for Debye full avg and for Debye with beta.

**Comment by krzywon** [comment]
@butlerpd - I just ran all GSC calculations (Fixed Orientation, Debye and Debye with Beta(Q)) and then successfully saved a project. This should be ready to merge, but the only thing holding this up now is your change request. Please test and give a final review when you are able.

**Review by butlerpd — APPROVED** [review]
agreed that it seems fixed for all things I can try. Not sure how to remove my change request other than to submit a new approval?

**Pull request merged**
