### PR TITLE
Add OSX Build Instructions

### PR DESCRIPTION
**Pull request by robertdfrench**
This is all that was necessary to build SasView from scratch on El Capitan. If it is suitable to merge this, I would like to update the docs to advise folks to:

1. Install homebrew
1. `source mac_setup.sh`

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
Hi Robert, Can create a sasview branch and then reopen a pull request? I want to test it through jenkins server and I cannot access your repo - I suppose.

**Comment by robertdfrench** [comment]
Ah, okay that makes sense. I think a homebrew package would be good for users, but necessarily amenable to setting up a development environment as per @pkienzle's concerns. What about a `mac_setup_development_environment.sh` or some such that relies on conda, and then I could (under a separate ticket) submit a SasView package to Homebrew?

**Comment by robertdfrench** [comment]
@wpotrzebowski just to check, you want me to open a branch on this repo instead of submitting PR from a fork? Sounds good. I will do that when I hear back from @pkienzle or @ajj.

**Comment by robertdfrench** [comment]
Ahh, no merges to master until 4.1. Got it. Fair enough!

**Pull request closed without merging**
