### PR TITLE
radius_effective update for smeared data

### PR DESCRIPTION
**Pull request by rozyczko**
Bring intermediate results back when smearing is on and display radius_effective. #2009

After all this was a SasView issue, although it did look like it originated in SasModels...

This assumes SasModels returns properly smeared P(Q) and S(Q) so we don't have to do it in `ModelThread` as it is currently done. Quick test shows this is the case but more careful check should be done before merge.

`100nmPinholeSphere` file, sphere/sphere/hardsphere, fitted `radius` only.

left: existing 5.0.5rc2, right: from this PR
smeared_intermediates

### CODE REVIEW

**Comment by gonzalezma** [comment]
I repeated my test (sphere * hayter_msa) with and without smearing and got the expected results (same as in version 4..2.2), and now with radius_effective being correctly updated and formatted, so it looks good to me.

**Review by smk78 — APPROVED** [review]
Functionality review building this branch on W10/x64. Repeated my original test using the hSDS_D2O_2p0_percent.xml and fitting to sphere*hayter_msa without & with smearing, _radius_effective_ now updates as expected, and the precision reported has been sanitised too! Thumbs up from me!

**Comment by butlerpd** [comment]
Do we know why the mac OS installers are failing on this PR?

Question based on previous conversations, mostly around the fact that the value was properly returned without smearing but not with smearing: Is this a hack just for the smeared case that we should tag needs to be revisited to address properly? or is this the correct fix that duplicates what was being done for the unsmeared case?

NOTE: this should be merged to release either way. The question is simply about whether we should consider the case closed or need to submit a follow on ticket for 5.1?

Also I note that line 182 in ModelThread.py (just above the line 183 which is the one changed for this PR) is a comment 
```
     # TODO: implement intermediate results in smearers
```
which seems to be what this is doing? so should that be removed now?

**Comment by rozyczko** [comment]
> Do we know why the mac OS installers are failing on this PR?

I think it had to do with the Qt version and it will/would be fixed when @wpotrzebowski merges #2021 

> Question based on previous conversations, mostly around the fact that the value was properly returned without smearing but > not with smearing: Is this a hack just for the smeared case that we should tag needs to be revisited to address properly? or is > this the correct fix that duplicates what was being done for the unsmeared case?

The latter. This isn't a hack but extension of what Torin coded originally, 3 years ago.

> Also I note that line 182 in ModelThread.py (just above the line 183 which is the one changed for this PR) is a comment
> which seems to be what this is doing? so should that be removed now?

If this indeed works as we expected for all cases, then yes, this can be removed and the code simplified. I am not familiar with possible use/edge cases so I'll leave proper testing to others.

**Review by butlerpd — APPROVED** [review]
Code changes are minimal and two reviewers have approved that the functionality is as expected. The macOS issues should now have been fixed and merged.  The changes to release_5.0.5 could be merged into this branch to verify before merging this back into the release branch but given the actual changes I do not see why that would be necessary and recommend we just merge now.

**Comment by wpotrzebowski** [comment]
I've just merged it with release_5.0.5 branch. I will test Mac OSX installer once it is build and I have time to do so (hopefully today).

**Comment by wpotrzebowski** [comment]
Tested on Mac. Works fine.

**Comment by RichardHeenan** [comment]
Testing local build of 5.0.5_pre_release_setup and 1.0.6_pre_release_setup on Windows, all qualitatively seems to do as expected trying core_shell_sphere times hardsphere with various combinations of polydispersity, radius_effective choice, smearing and beta(Q),  

(Glad to see that Torin had left a "TODO" in the appropriate place to fix this issue, Sorry that the tester likely never tried anything with smearing included, or maybe he forgot to progress the addition of smearing )

However after creating Graph3 with the separate P(Q), S(Q), beta(Q), and Seff(Q), I then appended the fit to Graph3. After a short while the fit on Graph1 stopped updating on subsequent fits. After this first happened I restarted sasview, but then it occurred again. Have not yet worked out how to reproducibly demonstrate this, as I was turning on/off various features here.

Also noted that the separate P(Q) and S(Q) are not smeared, presume this is what we expect???

**Comment by butlerpd** [comment]
Interesting point about P and S not being smeared.  That is I think what was envisaged but now that you mention it @RichardHeenan, one could ask the question. I think I would want to keep the pure, unsmeared versions, but would it also be useful to have the smeared version which would then give rise to the actual smeared curve? I would think yes... but then I start worrying about confusing people with the infinite list of subplots?  Not sure what the best answer is but access to a smeared version of P and S seems like a good idea? Maybe we should add this to one of the discussion tickets on plotting?

As for the fit question, I'm pretty sure I've seen similar things before.  As I recall the updating happens on the new "Graph3" rather than the original fit plot which seems to be "orphaned?"  I thought there was a ticket about that at one point but I' not finding it right away.... I suppose if it does not exist (except in my imagination 😄 ) we should create one.

**Pull request merged**
