### PR TITLE
Pull Request Testing any commit

### PR DESCRIPTION
**Pull request by wpotrzebowski**
This pull request has been opened to test jenkins plugin. Please don't do anything with it.

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready fro testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux_PRB

**Comment by wpotrzebowski** [comment]
ready for testing on Linux_PRB

**Comment by wpotrzebowski** [comment]
ready for testing on Linux_PRB

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by trnielsen** [comment]
ready for testing on OSX

**Comment by trnielsen** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on OSX

**Comment by wpotrzebowski** [comment]
ready for testing on Win32

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Comment by trnielsen** [comment]
ready for testing on Linux

**Comment by wpotrzebowski** [comment]
ready for testing on Linux

**Pull request closed without merging**
